import { getPocketBase, pocketBaseMessage } from './client.js';

function client() { const pb=getPocketBase(); if(!pb?.authStore.isValid) throw new Error('Sesi PocketBase tidak tersedia.'); return pb; }
function message(row){const pb=client();return{id:row.id,channelId:row.channelId,penulis:row.authorName,peran:row.authorLabel,waktu:new Date(row.createdAt),isi:row.content,saya:row.authorId===pb.authStore.record?.id,reaksi:(row.reactions||[]).map(x=>({emoji:x.emoji,jumlah:x.count,dipilih:Boolean(x.selected)}))}}
export async function listForumChannels(){try{return (await client().send('/api/pfriends/forum/channels')).items||[]}catch(error){throw new Error(pocketBaseMessage(error,'Kanal Forum gagal dimuat.'))}}
export async function listForumMessages(slug,{before='',perPage=50}={}){try{const query=new URLSearchParams({perPage:String(perPage)});if(before)query.set('before',before);const data=await client().send(`/api/pfriends/forum/channels/${encodeURIComponent(slug)}/messages?${query}`);return{items:(data.items||[]).map(message),hasMore:Boolean(data.hasMore),nextCursor:data.nextCursor||''}}catch(error){throw new Error(pocketBaseMessage(error,'Percakapan Forum gagal dimuat.'))}}
export async function sendForumMessage(slug,content,requestKey){try{return message(await client().send(`/api/pfriends/forum/channels/${encodeURIComponent(slug)}/messages`,{method:'POST',body:{content,requestKey}}))}catch(error){throw new Error(pocketBaseMessage(error,'Pesan gagal dikirim.'))}}
export async function setForumReaction(id,emoji,selected){try{const data=await client().send(`/api/pfriends/forum/messages/${id}/reaction`,{method:'POST',body:{emoji,selected}});return(data.reactions||[]).map(x=>({emoji:x.emoji,jumlah:x.count,dipilih:Boolean(x.selected)}))}catch(error){throw new Error(pocketBaseMessage(error,'Reaksi gagal disimpan.'))}}
export async function heartbeatForum(slug){try{await client().send('/api/pfriends/forum/presence/heartbeat',{method:'POST',body:{channel:slug}})}catch(error){throw new Error(pocketBaseMessage(error,'Status kehadiran gagal diperbarui.'))}}
export async function listForumPresence(){try{return(await client().send('/api/pfriends/forum/presence')).items||[]}catch(error){throw new Error(pocketBaseMessage(error,'Anggota daring gagal dimuat.'))}}
export async function subscribeForum(topic,callback){const pb=client();await pb.realtime.subscribe(topic,(event)=>callback(event));return()=>pb.realtime.unsubscribe(topic)}
