<script>
	import { Button, EmptyState, PageHeader, StatusBadge, ICONS } from '$lib/components';
	import { adminBroadcasts, publishBroadcast, saveBroadcast } from '$lib/infrastructure/pocketbase/broadcasts.js';
	import { toast } from '$lib/stores/toast.svelte.js';
	let rows=$state.raw([]), loading=$state(true), saving=$state(false), editing=$state('');
	const kosong=()=>({title:'',summary:'',body:'',channel:'SEMUA',contentSource:'Pertamina Foundation',lightCta:'',ctaLink:'',audience:'SEMUA',scheduledAt:''}); let form=$state(kosong());
	async function load(){loading=true;try{rows=await adminBroadcasts()}catch(e){toast.error('Kabar gagal dimuat',e.message)}finally{loading=false}}
	function edit(row){editing=row.id;form={...kosong(),...row,scheduledAt:row.scheduledAt?String(row.scheduledAt).slice(0,16):''}}
	async function submit(){saving=true;try{await saveBroadcast($state.snapshot(form),editing);toast.success(form.scheduledAt?'Kabar dijadwalkan':'Draf tersimpan',form.scheduledAt?'Kabar terbit otomatis sesuai jadwal.':'Tekan Terbitkan pada kartu agar terlihat oleh Awardee.');editing='';form=kosong();await load()}catch(e){toast.error('Kabar gagal disimpan',e.message)}finally{saving=false}}
	async function publish(id){saving=true;try{await publishBroadcast(id);toast.success('Kabar diterbitkan');await load()}catch(e){toast.error('Kabar gagal diterbitkan',e.message)}finally{saving=false}}
	$effect(()=>{load()});
</script>
<svelte:head><title>Pengelolaan Kabar · PFriends</title></svelte:head>
<PageHeader eyebrow="Diseminasi" title="Pengelolaan Kabar" subtitle="Susun, jadwalkan, dan terbitkan kabar nyata untuk Awardee." />
<div class="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(320px,430px)]">
	<section><h2 class="text-lg font-bold text-heading">Daftar kabar</h2>{#if loading}<p class="mt-4 text-sm text-ink-600">Memuat kabar…</p>{:else if rows.length===0}<div class="mt-4"><EmptyState title="Belum ada kabar" message="Buat kabar pertama melalui formulir di samping." iconPath={ICONS.megaphone}/></div>{:else}<div class="mt-4 space-y-3">{#each rows as row (row.id)}<article class="card p-4"><div class="flex justify-between gap-3"><div><StatusBadge label={row.status} color={row.status==='TERKIRIM'?'green':row.status==='TERJADWAL'?'blue':'slate'} /><h3 class="mt-2 font-bold text-heading">{row.title}</h3><p class="mt-1 text-sm text-ink-600">{row.summary}</p><p class="mt-2 text-xs text-ink-600">Penerima: {row.recipientCount || 0}</p></div><div class="flex shrink-0 flex-col gap-2">{#if row.status!=='TERKIRIM'}<Button size="sm" variant="secondary" onclick={()=>edit(row)}>Sunting</Button><Button size="sm" onclick={()=>publish(row.id)}>Terbitkan</Button>{/if}</div></div></article>{/each}</div>{/if}</section>
	<section class="card h-fit p-5"><h2 class="font-bold text-heading">{editing?'Sunting kabar':'Buat kabar'}</h2><div class="mt-4 space-y-3"><label class="block"><span class="label-micro">Judul</span><input class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.title}/></label><label class="block"><span class="label-micro">Ringkasan</span><textarea class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.summary}></textarea></label><label class="block"><span class="label-micro">Isi kabar</span><textarea rows="7" class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.body}></textarea></label><div class="grid gap-3 sm:grid-cols-2"><label><span class="label-micro">Kanal</span><select class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.channel}><option value="SEMUA">Semua kanal</option><option value="WA_KOMUNITAS">WA Komunitas</option><option value="MICROSITE">Microsite</option><option value="EMAIL">Email</option></select></label><label><span class="label-micro">Audiens</span><select class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.audience}><option value="SEMUA">Semua Awardee</option><option value="SOBI">SOBI</option><option value="WOMENPRENEUR">Womenpreneur</option></select></label></div><label class="block"><span class="label-micro">Ajakan ringan (opsional)</span><textarea class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.lightCta}></textarea></label><label class="block"><span class="label-micro">Jadwalkan (opsional)</span><input type="datetime-local" class="mt-1 w-full rounded-control border border-ink-200 p-2.5" bind:value={form.scheduledAt}/></label><div class="flex justify-end gap-2">{#if editing}<Button variant="ghost" onclick={()=>{editing='';form=kosong()}}>Batal</Button>{/if}<Button loading={saving} onclick={submit}>Simpan</Button></div></div></section>
</div>
