import emojiSource from '../../../../pocketbase/pb_hooks/forum-emoji-allowlist.js?raw';
import { apiRoute, noContent } from '../api-router.js';
import { ApiError } from '../auth.js';
import { recordId } from '../registration.js';

const EMOJIS = new Set(JSON.parse(emojiSource.slice(emojiSource.indexOf('['), emojiSource.lastIndexOf(']') + 1)));
function text(value) { return String(value ?? '').trim(); }
async function context(ctx) { const principal = await ctx.principal(); return { principal, pb: await ctx.admin() }; }
async function optionalOne(pb, collection, query) { try { return await pb.collection(collection).getFirstListItem(query); } catch (error) { if (error?.status === 404) return null; throw error; } }
async function awardee(pb, principal) { return principal.role === 'AWARDEE' ? optionalOne(pb, 'awardees', pb.filter('user = {:user}', { user: principal.record.id })) : null; }
function canRead(principal, profile, channel) { if (!channel.active) return false; if (principal.role !== 'AWARDEE') return true; return !channel.community || Boolean(profile && profile.status === 'AKTIF' && profile.community === channel.community); }
function canWrite(principal, profile, channel) { return canRead(principal, profile, channel) && (principal.role !== 'AWARDEE' || !channel.staffOnlyWrite); }
function identity(principal, profile) { if (principal.role !== 'AWARDEE') return { name: principal.record.displayName, label: principal.role === 'ADMIN' ? 'Admin Pertamina Foundation' : 'Verifikator PFriends' }; return profile ? { name: profile.fullName, label: profile.community === 'SOBI' ? `SOBI · ${profile.chapterId}` : `Womenpreneur · ${profile.businessName || profile.city}` } : { name: principal.record.displayName, label: 'Awardee PFriends' }; }
function reactionDtos(reactions, messageId, userId) { const counts = {}; for (const row of reactions.filter((item) => item.message === messageId)) { if (!counts[row.emoji]) counts[row.emoji] = { emoji: row.emoji, count: 0, selected: false }; counts[row.emoji].count++; if (row.user === userId) counts[row.emoji].selected = true; } return Object.values(counts).sort((a, b) => b.count - a.count || a.emoji.localeCompare(b.emoji)); }
function messageDto(row, messages, reactions, principal) { const parent = row.replyTo ? messages.find((item) => item.id === row.replyTo) : null, mine = row.author === principal.record.id; return { id: row.id, channelId: row.channel, authorId: row.author, authorKind: row.authorKind, authorName: row.authorName, authorLabel: row.authorLabel, content: row.content, mine, canDelete: row.authorKind !== 'SYSTEM' && (mine || ['ADMIN', 'VERIFIER'].includes(principal.role)), createdAt: row.sentAt, reply: parent ? { id: parent.id, authorName: parent.authorName, content: String(parent.content).slice(0, 180) } : null, reactions: reactionDtos(reactions, row.id, principal.record.id) }; }
async function messageData(pb) { return Promise.all([pb.collection('forum_messages').getFullList(), pb.collection('forum_reactions').getFullList()]); }

apiRoute('GET', '/forum/channels', async (ctx) => { const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), rows = await pb.collection('forum_channels').getFullList({ filter: 'active = true', sort: 'position' }); return { items: rows.filter((row) => canRead(principal, profile, row)).map((row) => ({ id: row.id, slug: row.slug, name: row.name, topic: row.topic, note: row.note || '', community: row.community || '', canPost: canWrite(principal, profile, row) })) }; });
apiRoute('GET', '/forum/channels/{slug}/messages', async (ctx) => {
	const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), channel = await pb.collection('forum_channels').getFirstListItem(pb.filter('slug = {:slug}', { slug: ctx.params.slug })); if (!canRead(principal, profile, channel)) throw new ApiError(403, 'Kanal tidak dapat diakses.');
	const before = text(ctx.url.searchParams.get('before')), limit = Math.min(50, Math.max(1, Number(ctx.url.searchParams.get('perPage') || 50))), filter = before ? pb.filter('channel = {:channel} && sentAt < {:before}', { channel: channel.id, before }) : pb.filter('channel = {:channel}', { channel: channel.id }), page = await pb.collection('forum_messages').getList(1, limit + 1, { filter, sort: '-sentAt' }), hasMore = page.items.length > limit, visible = page.items.slice(0, limit).reverse(), [messages, reactions] = await messageData(pb);
	return { items: visible.map((row) => messageDto(row, messages, reactions, principal)), hasMore, nextCursor: hasMore ? page.items[limit - 1].sentAt : '' };
});
apiRoute('GET', '/forum/messages/{id}/context', async (ctx) => { const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), target = await pb.collection('forum_messages').getOne(ctx.params.id), channel = await pb.collection('forum_channels').getOne(target.channel); if (!canRead(principal, profile, channel)) throw new ApiError(403, 'Pesan tidak dapat diakses.'); const [messages, reactions] = await messageData(pb), sorted = messages.filter((row) => row.channel === channel.id).sort((a, b) => new Date(a.sentAt) - new Date(b.sentAt)), index = sorted.findIndex((row) => row.id === target.id), rows = sorted.slice(Math.max(0, index - 20), index + 21); return { channelSlug: channel.slug, items: rows.map((row) => messageDto(row, messages, reactions, principal)) }; });
apiRoute('POST', '/forum/channels/{slug}/messages', async (ctx) => {
	const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), channel = await pb.collection('forum_channels').getFirstListItem(pb.filter('slug = {:slug}', { slug: ctx.params.slug })); if (!canWrite(principal, profile, channel)) throw new ApiError(403, 'Anda tidak dapat menulis di kanal ini.'); const body = await ctx.body(), content = text(body.content), requestKey = text(body.requestKey), replyTo = text(body.replyTo); if (!content || content.length > 600) throw new ApiError(400, 'Pesan wajib berisi 1 sampai 600 karakter.'); if (!requestKey) throw new ApiError(400, 'requestKey wajib diisi.');
	let parent = null; if (replyTo) { parent = await pb.collection('forum_messages').getOne(replyTo); if (parent.channel !== channel.id) throw new ApiError(400, 'Pesan balasan harus berada di kanal yang sama.'); }
	let row = await optionalOne(pb, 'forum_messages', pb.filter('author = {:author} && requestKey = {:key}', { author: principal.record.id, key: requestKey }));
	if (!row) { const now = Date.now(), messages = await pb.collection('forum_messages').getFullList({ filter: pb.filter('author = {:author}', { author: principal.record.id }), sort: '-sentAt' }), recent30 = messages.filter((item) => new Date(item.sentAt).getTime() > now - 30000), recent10m = messages.filter((item) => new Date(item.sentAt).getTime() > now - 600000), duplicate = messages.some((item) => item.channel === channel.id && new Date(item.sentAt).getTime() > now - 120000 && text(item.content) === content); if (recent30.length >= 6) throw new ApiError(429, 'Batas enam pesan per 30 detik tercapai. Coba lagi sebentar.'); if (recent10m.length >= 30) throw new ApiError(429, 'Batas 30 pesan per sepuluh menit tercapai.'); if (duplicate) throw new ApiError(429, 'Pesan yang sama baru saja dikirim.'); const who = identity(principal, profile); row = await pb.collection('forum_messages').create({ id: recordId(), channel: channel.id, author: principal.record.id, authorKind: 'USER', authorName: who.name, authorLabel: who.label, content, requestKey, replyTo: parent?.id || '', sentAt: new Date().toISOString() }); }
	const [messages, reactions] = await messageData(pb); return { status: 201, body: messageDto(row, messages, reactions, principal) };
});
apiRoute('POST', '/forum/messages/{id}/reaction', async (ctx) => { const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), message = await pb.collection('forum_messages').getOne(ctx.params.id), channel = await pb.collection('forum_channels').getOne(message.channel); if (!canRead(principal, profile, channel)) throw new ApiError(403, 'Pesan tidak dapat diakses.'); const body = await ctx.body(), emoji = String(body.emoji || ''); if (!EMOJIS.has(emoji)) throw new ApiError(400, 'Reaksi tidak didukung.'); const row = await optionalOne(pb, 'forum_reactions', pb.filter('message = {:message} && user = {:user} && emoji = {:emoji}', { message: message.id, user: principal.record.id, emoji })); if (body.selected && !row) await pb.collection('forum_reactions').create({ id: recordId(), message: message.id, user: principal.record.id, emoji }); else if (!body.selected && row) await pb.collection('forum_reactions').delete(row.id); const reactions = await pb.collection('forum_reactions').getFullList(); return { reactions: reactionDtos(reactions, message.id, principal.record.id) }; });
apiRoute('DELETE', '/forum/messages/{id}', async (ctx) => { const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), message = await pb.collection('forum_messages').getOne(ctx.params.id), channel = await pb.collection('forum_channels').getOne(message.channel); if (!canRead(principal, profile, channel)) throw new ApiError(403, 'Pesan tidak dapat diakses.'); if (message.authorKind === 'SYSTEM') throw new ApiError(403, 'Pesan sistem tidak dapat dihapus.'); if (message.author !== principal.record.id && !['ADMIN', 'VERIFIER'].includes(principal.role)) throw new ApiError(403, 'Anda tidak dapat menghapus pesan ini.'); await pb.collection('forum_messages').delete(message.id); return noContent(); });
apiRoute('POST', '/forum/presence/heartbeat', async (ctx) => { const { principal, pb } = await context(ctx), profile = await awardee(pb, principal), body = await ctx.body(); let channel = null; if (body.channel) { channel = await pb.collection('forum_channels').getFirstListItem(pb.filter('slug = {:slug}', { slug: body.channel })); if (!canRead(principal, profile, channel)) throw new ApiError(403, 'Kanal tidak dapat diakses.'); } const row = await optionalOne(pb, 'forum_presences', pb.filter('user = {:user}', { user: principal.record.id })), data = { user: principal.record.id, channel: channel?.id || '', lastSeenAt: new Date().toISOString() }; if (row) await pb.collection('forum_presences').update(row.id, data); else await pb.collection('forum_presences').create({ id: recordId(), ...data }); return noContent(); });
apiRoute('GET', '/forum/presence', async (ctx) => { const { pb } = await context(ctx), now = Date.now(), cutoff = new Date(now - 300000).toISOString(), [rows, users, awardees] = await Promise.all([pb.collection('forum_presences').getList(1, 50, { filter: pb.filter('lastSeenAt >= {:cutoff}', { cutoff }), sort: '-lastSeenAt' }), pb.collection('users').getFullList(), pb.collection('awardees').getFullList()]), userBy = new Map(users.map((row) => [row.id, row])), awardeeBy = new Map(awardees.map((row) => [row.user, row])); return { items: rows.items.map((row) => { const user = userBy.get(row.user), principal = { role: user.role, record: user }, who = identity(principal, awardeeBy.get(user.id)), age = now - new Date(row.lastSeenAt).getTime(); return { id: user.id, name: who.name, label: who.label, state: age <= 90000 ? 'aktif' : 'sibuk' }; }) }; });
