import { listForumChannels,listForumMessages,sendForumMessage,setForumReaction,heartbeatForum,listForumPresence,subscribeForum } from '$lib/infrastructure/pocketbase/forum.js';

class ForumStore {
	channels=$state.raw([]); messages=$state.raw({}); presence=$state.raw([]); loading=$state(false); sending=$state(false); error=$state(null); activeSlug=$state('');
	#channelUnsubscribe=null; #presenceUnsubscribe=null; #heartbeat=null;
	async load(){this.loading=true;this.error=null;this.messages={};this.presence=[];try{this.channels=await listForumChannels();if(!this.activeSlug||!this.channels.some(x=>x.slug===this.activeSlug))this.activeSlug=this.channels.find(x=>x.slug==='sobi-alumni')?.slug||this.channels[0]?.slug||'';if(this.activeSlug)await this.open(this.activeSlug);await this.refreshPresence();await this.#subscribePresence();this.#startHeartbeat()}catch(error){this.error=error instanceof Error?error.message:'Forum gagal dimuat.'}finally{this.loading=false}}
	async open(slug){const channel=this.channels.find(x=>x.slug===slug);if(!channel)return;this.activeSlug=slug;if(!this.messages[slug]){const page=await listForumMessages(slug);this.messages={...this.messages,[slug]:page.items};this.channels=this.channels.map(x=>x.slug===slug?{...x,hasMore:page.hasMore,nextCursor:page.nextCursor}:x)}if(this.#channelUnsubscribe)await this.#channelUnsubscribe();this.#channelUnsubscribe=await subscribeForum(`forum:channel:${channel.id}`,(event)=>this.#event(slug,event));await this.beat()}
	async older(){const channel=this.channels.find(x=>x.slug===this.activeSlug);if(!channel?.hasMore)return;const page=await listForumMessages(channel.slug,{before:channel.nextCursor});this.messages={...this.messages,[channel.slug]:[...page.items,...(this.messages[channel.slug]||[])]};this.channels=this.channels.map(x=>x.slug===channel.slug?{...x,hasMore:page.hasMore,nextCursor:page.nextCursor}:x)}
	async send(content){const slug=this.activeSlug;if(!content.trim()||this.sending)return null;this.sending=true;try{const row=await sendForumMessage(slug,content.trim(),crypto.randomUUID());const rows=this.messages[slug]||[],found=rows.some(x=>x.id===row.id);this.messages={...this.messages,[slug]:found?rows.map(x=>x.id===row.id?row:x):[...rows,row]};return row}catch(error){this.error=error instanceof Error?error.message:'Pesan gagal dikirim.';throw error}finally{this.sending=false}}
	async react(message,emoji){const selected=!message.reaksi.find(x=>x.emoji===emoji)?.dipilih;message.reaksi=await setForumReaction(message.id,emoji,selected);this.messages={...this.messages,[this.activeSlug]:[...(this.messages[this.activeSlug]||[])]}}
	async beat(){if(!this.activeSlug)return;await heartbeatForum(this.activeSlug)}
	async refreshPresence(){this.presence=await listForumPresence()}
	async #subscribePresence(){if(this.#presenceUnsubscribe)return;this.#presenceUnsubscribe=await subscribeForum('forum:presence',()=>this.refreshPresence().catch(()=>{}))}
	#startHeartbeat(){if(this.#heartbeat)return;this.#heartbeat=setInterval(()=>{if(document.visibilityState==='visible')this.beat().catch(()=>{})},60000)}
	#event(slug,event){const data=event?.data||event;if(data.type==='message.created'){const row=data.message;const normalized={id:row.id,channelId:row.channelId,penulis:row.authorName,peran:row.authorLabel,waktu:new Date(row.createdAt),isi:row.content,saya:false,reaksi:(row.reactions||[]).map(x=>({emoji:x.emoji,jumlah:x.count,dipilih:false}))};const rows=this.messages[slug]||[];if(!rows.some(x=>x.id===normalized.id))this.messages={...this.messages,[slug]:[...rows,normalized]}}else if(data.type==='message.reactions'){const rows=(this.messages[slug]||[]).map(row=>row.id===data.messageId?{...row,reaksi:data.reactions.map(x=>({emoji:x.emoji,jumlah:x.count,dipilih:row.reaksi.find(y=>y.emoji===x.emoji)?.dipilih||false}))}:row);this.messages={...this.messages,[slug]:rows}}}
	async destroy(){if(this.#channelUnsubscribe)await this.#channelUnsubscribe();if(this.#presenceUnsubscribe)await this.#presenceUnsubscribe();if(this.#heartbeat)clearInterval(this.#heartbeat);this.#channelUnsubscribe=null;this.#presenceUnsubscribe=null;this.#heartbeat=null}
}
export const forum=new ForumStore();
