<script>
	import { onMount, tick } from 'svelte';
	import { Avatar, Card, Icon, ICONS } from '$lib/components';
	import EmojiReactionPicker from '$lib/components/EmojiReactionPicker.svelte';
	import ForumModerationPanel from '$lib/components/ForumModerationPanel.svelte';
	import { forum } from '$lib/stores/forum.svelte.js';
	import { session } from '$lib/stores/session.svelte.js';
	import { toast } from '$lib/stores/toast.svelte.js';
	import { frasaHitung, inisial } from '$lib/utils/format.js';
	const AMBANG_GABUNG_MENIT=8, BATAS_KARAKTER=600;
	const tanggalForum=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',weekday:'long',day:'numeric',month:'long',year:'numeric'});
	const jamForum=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
	let draf=$state(''), wadahPesan=$state(null), kotakPesan=$state(null), menuPesanId=$state(''), pickerPesanId=$state(''), balasKe=$state(null), sorotId=$state(''), timerTutupMenu;
	let pencarianTerbuka=$state(false), hasilTerlihat=$state(false), inputCari=$state(null), kataCari=$state(''), hasilCari=$state.raw([]), jumlahHasil=$state(0), hasilAktif=$state(-1), sedangMencari=$state(false), galatCari=$state(''), timerCari, generasiCari=0, posisiSebelumCari=0;
	let panelModerasi=$state(false), targetModerasi=$state('');
	const kanal=$derived(forum.channels.find(x=>x.slug===forum.activeSlug)??forum.channels[0]);
	const staf=$derived(session.isAdmin||session.isVerifier);
	function kunciHari(input){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(input)}
	function labelTanggal(input){return tanggalForum.format(input)}
	function labelJam(input){return `${jamForum.format(input).replace(':','.')} WIB`}
	const pesanTampil=$derived.by(()=>{const rows=forum.messages[forum.activeSlug]??[];return rows.map((pesan,index)=>{const before=rows[index-1],hari=kunciHari(pesan.waktu),hariSebelumnya=before?kunciHari(before.waktu):'',gantiHari=!before||hari!==hariSebelumnya,gap=before?(pesan.waktu-before.waktu)/60000:Infinity;return{...pesan,gantiHari,gabung:!gantiHari&&!pesan.balasan&&Boolean(before)&&before.penulis===pesan.penulis&&gap<AMBANG_GABUNG_MENIT}})});
	const dapatKirim=$derived(Boolean(kanal?.canPost&&draf.trim()&&!forum.sending));
	const jumlahAktif=$derived(forum.presence.filter(x=>x.state==='aktif').length);
	async function gulirKeBawah(){await tick();if(wadahPesan)wadahPesan.scrollTop=wadahPesan.scrollHeight}
	async function bukaKanal(slug){menuPesanId='';pickerPesanId='';balasKe=null;tutupPencarian(false);await forum.open(slug);await gulirKeBawah()}
	async function kirim(){const isi=draf.trim(),replyTo=balasKe?.id||'';if(!isi||!kanal?.canPost)return;draf='';try{await forum.send(isi,replyTo);balasKe=null;await gulirKeBawah()}catch(error){draf=isi;toast.error('Pesan belum terkirim',error instanceof Error?error.message:'Coba kirim kembali.')}}
	function tekanTombol(event){if(event.key!=='Enter'||event.shiftKey)return;event.preventDefault();void kirim()}
	async function reaksi(pesan,emoji){try{await forum.react(pesan,emoji)}catch(error){toast.error('Reaksi belum tersimpan',error instanceof Error?error.message:'Coba lagi.')}}
	async function hapusPesan(pesan){menuPesanId='';pickerPesanId='';try{await forum.remove(pesan);toast.success('Pesan dihapus')}catch(error){toast.error('Pesan belum dihapus',error instanceof Error?error.message:'Coba lagi.')}}
	async function pilihReaksi(pesan,emoji){pickerPesanId='';await reaksi(pesan,emoji)}
	function bukaMenuHover(id){if(timerTutupMenu)clearTimeout(timerTutupMenu);timerTutupMenu=undefined;if(!pickerPesanId)menuPesanId=id}
	function jadwalkanTutupMenu(id){if(timerTutupMenu)clearTimeout(timerTutupMenu);timerTutupMenu=setTimeout(()=>{if(menuPesanId===id&&pickerPesanId!==id)menuPesanId=''},300)}
	async function mulaiBalas(pesan){balasKe={id:pesan.id,penulis:pesan.penulis,isi:pesan.isi};menuPesanId='';pickerPesanId='';await tick();kotakPesan?.focus()}
	async function menujuPesan(id){let element=document.querySelector(`[data-forum-message="${id}"]`);if(!element){try{await forum.context(id);await tick();element=document.querySelector(`[data-forum-message="${id}"]`)}catch(error){toast.error('Pesan asal belum ditemukan',error instanceof Error?error.message:'Coba lagi.')}}if(element){element.scrollIntoView({behavior:'smooth',block:'center'});sorotId=id;setTimeout(()=>{if(sorotId===id)sorotId=''},2200)}}
	async function bukaPencarian(){posisiSebelumCari=wadahPesan?.scrollTop??0;pencarianTerbuka=true;await tick();inputCari?.focus()}
	function tutupPencarian(kembalikanPosisi=true){if(timerCari)clearTimeout(timerCari);generasiCari++;pencarianTerbuka=false;hasilTerlihat=false;kataCari='';hasilCari=[];jumlahHasil=0;hasilAktif=-1;sedangMencari=false;galatCari='';if(kembalikanPosisi&&wadahPesan)wadahPesan.scrollTop=posisiSebelumCari}
	function jadwalkanPencarian(){if(timerCari)clearTimeout(timerCari);const query=kataCari.trim(),permintaan=++generasiCari;hasilTerlihat=true;hasilCari=[];jumlahHasil=0;hasilAktif=-1;galatCari='';sedangMencari=false;if(query.length<2)return;sedangMencari=true;timerCari=setTimeout(async()=>{try{const data=await forum.search(forum.activeSlug,query);if(permintaan!==generasiCari)return;hasilCari=data.items;jumlahHasil=data.totalItems;hasilAktif=data.items.length?0:-1}catch(error){if(permintaan===generasiCari)galatCari=error instanceof Error?error.message:'Pencarian pesan gagal dilakukan.'}finally{if(permintaan===generasiCari)sedangMencari=false}},700)}
	async function pilihHasil(index){if(!hasilCari.length)return;hasilAktif=(index+hasilCari.length)%hasilCari.length;hasilTerlihat=false;await menujuPesan(hasilCari[hasilAktif].id)}
	function bukaModerasi(userId=''){menuPesanId='';pickerPesanId='';targetModerasi=userId;panelModerasi=true}
	function tombolCari(event){if(event.key==='Escape')tutupPencarian();else if(event.key==='Enter'&&hasilCari.length){event.preventDefault();void pilihHasil(hasilAktif<0?0:hasilAktif)}}
	onMount(()=>{void forum.load().then(gulirKeBawah);return()=>{if(timerCari)clearTimeout(timerCari);void forum.destroy()}});
</script>

<svelte:window onclick={()=>hasilTerlihat=false}/>

<svelte:head><title>Forum Komunitas: PFriends</title></svelte:head>
<div class="mb-4"><p class="label-micro">Ruang percakapan PFriends</p><h1 class="mt-1 font-sans text-2xl font-bold tracking-[-0.02em] text-heading">Forum</h1><p class="mt-1.5 max-w-2xl text-sm leading-relaxed text-ink-600">Tempat alumni Sobat Bumi dan pelaku usaha PFpreneur saling menyapa, bertanya, dan berbagi kabar: dipisah per kanal supaya percakapan yang kamu cari tidak tenggelam.</p></div>
{#if forum.error}<div class="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900">{forum.error}</div>{/if}
{#if forum.connectionState==='fallback'}<div class="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900" role="status">Koneksi langsung sedang dipulihkan. Pesan tetap diperbarui otomatis.</div>{/if}
{#if forum.moderation.readOnly}<div class="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950" role="status"><strong>{forum.moderation.mode==='BANNED'?'Akses menulis Forum diblokir':'Anda sedang terkena timeout Forum'}.</strong> Anda masih dapat membaca dan mencari pesan, tetapi tidak dapat mengirim, bereaksi, atau menghapus pesan.{#if forum.moderation.reason}<span class="mt-1 block">Alasan: {forum.moderation.reason}</span>{/if}{#if forum.moderation.timeoutUntil}<span class="mt-1 block text-xs">Berakhir {labelTanggal(new Date(forum.moderation.timeoutUntil))} · {labelJam(new Date(forum.moderation.timeoutUntil))}</span>{/if}</div>{/if}
<div class="grid gap-4 lg:h-[calc(100vh-11rem)] lg:min-h-[540px] lg:grid-cols-[15rem_minmax(0,1fr)] xl:grid-cols-[15rem_minmax(0,1fr)_14rem]">
	<nav aria-label="Daftar kanal forum" class="min-w-0">
		<div class="hidden h-full flex-col rounded-card border border-ink-100 bg-surface p-2 lg:flex"><p class="label-micro px-2 pt-2 pb-3">Kanal komunitas</p><ul class="min-h-0 flex-1 space-y-1 overflow-y-auto">{#each forum.channels as item (item.id)}<li><button type="button" aria-current={item.slug===forum.activeSlug?'true':undefined} class="flex min-h-11 w-full items-center gap-2 rounded-xl px-2.5 text-sm transition-colors {item.slug===forum.activeSlug?'bg-pertamina-navy-tint font-semibold text-pertamina-navy':'font-medium text-ink-600 hover:bg-ink-50 hover:text-ink-800'}" onclick={()=>bukaKanal(item.slug)}><span class="shrink-0 text-base leading-none opacity-70" aria-hidden="true">#</span><span class="min-w-0 flex-1 truncate text-left">{item.name}</span>{#if item.slug==='pengumuman'}<Icon path={ICONS.megaphone} size={14}/>{/if}</button></li>{/each}</ul><div class="mt-2 shrink-0 border-t border-ink-100 px-2.5 pt-3 pb-1"><p class="text-[11px] leading-relaxed text-ink-600">Kanal baru dibuka atas usulan chapter. Sampaikan di #tanya-jawab bila komunitasmu membutuhkan ruangnya sendiri.</p></div></div>
		<ul class="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1 lg:hidden">{#each forum.channels as item (item.id)}<li class="shrink-0"><button type="button" aria-current={item.slug===forum.activeSlug?'true':undefined} class="inline-flex min-h-9 items-center rounded-chip border px-3 text-sm transition-colors {item.slug===forum.activeSlug?'border-pertamina-navy bg-pertamina-navy-tint font-semibold text-pertamina-navy':'border-ink-200 bg-surface font-medium text-ink-600'}" onclick={()=>bukaKanal(item.slug)}>#{item.name}</button></li>{/each}</ul>
	</nav>
	<section class="flex min-w-0 flex-col overflow-hidden rounded-card border border-ink-100 bg-surface" aria-label="Percakapan kanal {kanal?.name??''}">
		<header class="relative z-30 shrink-0 border-b border-ink-100 px-4 py-3" data-search-results-visible={hasilTerlihat}>
			<div class="flex items-start justify-between gap-3"><div class="min-w-0"><h2 class="flex items-center gap-1.5 text-base font-bold text-heading"><span class="text-ink-400" aria-hidden="true">#</span>{kanal?.name??'Memuat kanal'}</h2><p class="mt-0.5 truncate text-[13px] leading-relaxed text-ink-600">{kanal?.topic??''}</p></div>{#if !pencarianTerbuka}<button type="button" class="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-ink-600 hover:bg-ink-50 hover:text-heading" aria-label="Cari pesan di kanal {kanal?.name??''}" onclick={bukaPencarian}><Icon path={ICONS.search} size={19}/></button>{/if}</div>
			{#if staf&&!pencarianTerbuka}<button type="button" class="absolute top-3 right-16 inline-flex h-10 w-10 items-center justify-center rounded-xl text-ink-600 hover:bg-ink-50 hover:text-heading" aria-label="Buka moderasi Forum" onclick={()=>bukaModerasi()}><Icon path={ICONS.shield} size={19}/></button>{/if}
			{#if pencarianTerbuka}
				<div class="mt-3 flex items-center gap-2 rounded-xl border border-ink-200 bg-canvas p-1.5 focus-within:border-brand-400 focus-within:ring-2 focus-within:ring-brand-100"><Icon path={ICONS.search} size={17}/><input bind:this={inputCari} bind:value={kataCari} oninput={jadwalkanPencarian} onkeydown={tombolCari} type="search" minlength="2" maxlength="80" class="min-w-0 flex-1 border-0 bg-transparent px-1 py-1 text-sm text-heading outline-none focus:ring-0" placeholder="Cari di #{kanal?.name??'kanal'}" aria-label="Cari pesan di kanal {kanal?.name??''}" /><span class="numeric shrink-0 text-xs text-ink-500">{hasilCari.length?`${hasilAktif+1} / ${jumlahHasil}`:'0 hasil'}</span><button type="button" disabled={!hasilCari.length} class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-ink-600 hover:bg-white disabled:text-ink-300" aria-label="Hasil sebelumnya" onclick={()=>pilihHasil(hasilAktif-1)}><Icon path={ICONS.chevronUp} size={16}/></button><button type="button" disabled={!hasilCari.length} class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-ink-600 hover:bg-white disabled:text-ink-300" aria-label="Hasil berikutnya" onclick={()=>pilihHasil(hasilAktif+1)}><Icon path={ICONS.chevronDown} size={16}/></button><button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-ink-600 hover:bg-white" aria-label="Tutup pencarian" onclick={()=>tutupPencarian()}><Icon path={ICONS.x} size={16}/></button></div>
				{#if kataCari.trim().length===1}<p class="mt-2 text-xs text-ink-500">Ketik minimal dua karakter.</p>{:else if sedangMencari}<p class="mt-2 text-xs text-ink-500" role="status">Mencari pesan...</p>{:else if galatCari}<p class="mt-2 text-xs text-red-700" role="alert">{galatCari}</p>{:else if kataCari.trim().length>=2&&hasilCari.length===0}<p class="mt-2 text-xs text-ink-500">Tidak ada pesan yang cocok di #{kanal?.name}.</p>{/if}
				{#if hasilCari.length}<div class="absolute right-4 left-4 top-full max-h-72 overflow-y-auto rounded-b-xl border border-t-0 border-ink-200 bg-surface p-2 shadow-lg" aria-label="Hasil pencarian pesan"><p class="px-2 py-1 text-[11px] font-semibold text-ink-500">{jumlahHasil} pesan ditemukan di #{kanal?.name}</p>{#each hasilCari as hasil,index (hasil.id)}<button type="button" class="mt-1 block w-full rounded-xl px-3 py-2.5 text-left hover:bg-ink-50 {index===hasilAktif?'bg-brand-50 ring-1 ring-brand-100':''}" onclick={()=>pilihHasil(index)}><span class="flex items-center justify-between gap-3"><strong class="truncate text-xs text-heading">{hasil.authorName}</strong><time class="shrink-0 text-[10px] text-ink-500" datetime={hasil.waktu.toISOString()}>{labelTanggal(hasil.waktu)} · {labelJam(hasil.waktu)}</time></span><span class="mt-1 block line-clamp-2 text-xs leading-relaxed text-ink-600">{hasil.content}</span></button>{/each}{#if jumlahHasil>hasilCari.length}<p class="px-2 py-2 text-center text-[11px] text-ink-500">Menampilkan 20 hasil terbaru.</p>{/if}</div>{/if}
			{/if}
		</header>
		<div bind:this={wadahPesan} class="max-h-[52vh] min-h-0 flex-1 space-y-1 overflow-y-auto px-4 py-4 lg:max-h-none">
			{#if kanal}<div class="mb-4 rounded-xl bg-brand-50 px-3.5 py-3"><p class="text-[13px] leading-relaxed text-brand-700"><span class="font-semibold">Selamat datang di #{kanal.name}.</span> {kanal.note}</p></div>{/if}
			{#if kanal?.hasMore}<button type="button" class="mx-auto mb-3 block text-xs font-semibold text-brand-700" onclick={()=>forum.older()}>Muat pesan sebelumnya</button>{/if}
			{#if forum.loading&&pesanTampil.length===0}<p class="py-8 text-center text-sm text-ink-500">Memuat percakapan...</p>{:else if pesanTampil.length===0}<p class="py-8 text-center text-sm text-ink-500">Belum ada pesan di kanal ini.</p>{/if}
			{#each pesanTampil as pesan (pesan.id)}
				{#if pesan.gantiHari}<div class="relative my-5 flex items-center" role="separator" aria-label={labelTanggal(pesan.waktu)}><div class="h-px flex-1 bg-ink-200"></div><time datetime={pesan.waktu.toISOString()} class="mx-3 shrink-0 rounded-chip border border-ink-200 bg-surface px-3 py-1 text-[11px] font-semibold text-ink-600">{labelTanggal(pesan.waktu)}</time><div class="h-px flex-1 bg-ink-200"></div></div>{/if}
				<article data-forum-message={pesan.id} class="group relative flex gap-3 rounded-xl px-1.5 py-1 transition-colors hover:bg-ink-50 {pesan.gabung?'':'mt-3'} {sorotId===pesan.id?'bg-brand-50 ring-1 ring-brand-200':''}">
					<div class="w-9 shrink-0 pt-0.5">{#if pesan.gabung}<time datetime={pesan.waktu.toISOString()} class="numeric block pt-1 text-center text-[9px] font-medium text-ink-400" title={`${labelTanggal(pesan.waktu)}, ${labelJam(pesan.waktu)}`}>{labelJam(pesan.waktu).replace(' WIB','')}</time><span class="sr-only">{pesan.penulis}</span>{:else}<Avatar name={pesan.penulis} size="sm"/>{/if}</div>
					<div class="min-w-0 flex-1 pr-8">{#if !pesan.gabung}<p class="flex flex-wrap items-baseline gap-x-2 gap-y-0.5"><span class="text-sm font-bold {pesan.saya?'text-brand-700':'text-heading'}">{pesan.penulis}</span><span class="text-[11px] text-ink-500">{pesan.peran}</span><time datetime={pesan.waktu.toISOString()} class="numeric text-[11px] font-medium text-ink-500" title={`${labelTanggal(pesan.waktu)}, ${labelJam(pesan.waktu)}`}>{labelJam(pesan.waktu)}</time></p>{/if}{#if pesan.balasan}<button type="button" class="mt-1 block max-w-full border-l-2 border-ink-300 pl-2 text-left text-[11px] text-ink-500 hover:text-brand-700" onclick={()=>menujuPesan(pesan.balasan.id)}><span class="font-semibold">Membalas {pesan.balasan.penulis}</span><span class="block truncate">{pesan.balasan.isi}</span></button>{/if}<p class="mt-0.5 text-sm leading-relaxed break-words text-ink-700">{pesan.isi}</p>{#if pesan.reaksi.length}<ul class="mt-1.5 flex flex-wrap gap-1.5">{#each pesan.reaksi as item (item.emoji)}<li><button type="button" aria-pressed={item.dipilih} class="inline-flex items-center gap-1 rounded-chip border px-2 py-0.5 text-[11px] transition-colors {item.dipilih?'border-sky-400 bg-sky-100 font-semibold text-sky-800 ring-1 ring-sky-200':'border-ink-200 bg-ink-50 text-ink-700 hover:border-sky-300 hover:bg-sky-50'}" onclick={()=>reaksi(pesan,item.emoji)}><span aria-hidden="true">{item.emoji}</span><span class="numeric">{item.jumlah}</span></button></li>{/each}</ul>{/if}</div>
					<div class="absolute top-0.5 right-1 z-20 opacity-100 transition-opacity md:opacity-0 md:group-hover:opacity-100 md:group-focus-within:opacity-100" role="group" aria-label="Tindakan untuk pesan {pesan.penulis}" onmouseenter={()=>bukaMenuHover(pesan.id)} onmouseleave={()=>jadwalkanTutupMenu(pesan.id)}><button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-ink-200 bg-surface text-ink-600 shadow-sm hover:text-heading" aria-label="Tindakan pesan" aria-expanded={menuPesanId===pesan.id||pickerPesanId===pesan.id} onclick={()=>{pickerPesanId='';menuPesanId=menuPesanId===pesan.id?'':pesan.id}}><Icon path={ICONS.dots} size={17}/></button>{#if menuPesanId===pesan.id}<div class="absolute right-0 mt-1 w-44 rounded-xl border border-ink-200 bg-surface p-1 shadow-lg"><button type="button" class="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-ink-700 hover:bg-ink-50" onclick={()=>{menuPesanId='';pickerPesanId=pesan.id}}>Tambah reaksi</button><button type="button" class="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-ink-700 hover:bg-ink-50" onclick={()=>mulaiBalas(pesan)}>Balas</button>{#if staf&&!pesan.saya&&pesan.userId}<button type="button" class="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-amber-800 hover:bg-amber-50" onclick={()=>bukaModerasi(pesan.userId)}>Moderasi pengguna</button>{/if}{#if pesan.dapatHapus||pesan.saya}<button type="button" class="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-red-700 hover:bg-red-50" onclick={()=>hapusPesan(pesan)}>Hapus pesan</button>{/if}</div>{/if}{#if pickerPesanId===pesan.id}<EmojiReactionPicker onselect={(emoji)=>pilihReaksi(pesan,emoji)} onclose={()=>pickerPesanId=''}/>{/if}</div>
				</article>
			{/each}
		</div>
		<div class="shrink-0 border-t border-ink-100 bg-surface p-3">{#if balasKe}<div class="mb-2 flex items-center gap-2 rounded-xl bg-ink-50 px-3 py-2"><p class="min-w-0 flex-1 text-xs text-ink-600"><span class="font-semibold text-ink-800">Membalas {balasKe.penulis}</span><span class="block truncate">{balasKe.isi}</span></p><button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-ink-500 hover:bg-surface hover:text-heading" aria-label="Batalkan balasan" onclick={()=>balasKe=null}><Icon path={ICONS.x} size={16}/></button></div>{/if}<form class="flex items-end gap-2 rounded-xl border border-ink-200 bg-canvas p-2 focus-within:border-brand-300" onsubmit={(event)=>{event.preventDefault();void kirim()}}><label class="sr-only" for="kotak-pesan">Tulis pesan di kanal {kanal?.name??''}</label><textarea bind:this={kotakPesan} id="kotak-pesan" rows="1" maxlength={BATAS_KARAKTER} bind:value={draf} onkeydown={tekanTombol} disabled={!kanal?.canPost} placeholder={kanal?.canPost?`Tulis pesan di #${kanal.name}…`:'Kanal ini hanya dapat ditulis oleh staf.'} class="max-h-32 min-h-11 flex-1 resize-none border-0 bg-transparent px-2 py-2 text-sm leading-relaxed text-ink-800 placeholder:text-ink-500 focus:ring-0 disabled:cursor-not-allowed disabled:bg-transparent"></textarea><button type="submit" disabled={!dapatKirim} class="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-pertamina-red-ink text-white transition-colors hover:bg-pertamina-red-dark disabled:bg-ink-200 disabled:text-ink-500" aria-label="Kirim pesan"><Icon path={ICONS.arrowRight} size={18}/></button></form><p class="mt-1.5 px-1 text-[11px] text-ink-500">{kanal?.canPost?'Enter mengirim · Shift+Enter membuat baris baru':'Hanya Admin dan Verifikator yang dapat mengirim di kanal ini'} · {frasaHitung(pesanTampil.length,'pesan')} di kanal ini</p></div>
	</section>
	<aside class="hidden min-w-0 xl:block" aria-label="Anggota yang sedang daring"><Card padding="none" class="flex h-full flex-col overflow-hidden"><p class="label-micro shrink-0 px-4 pt-4 pb-3">Daring · {jumlahAktif}</p><ul class="min-h-0 flex-1 space-y-1 overflow-y-auto px-2 pb-3">{#each forum.presence as orang (orang.id)}<li class="flex items-center gap-2.5 rounded-xl px-2 py-1.5"><span class="relative shrink-0"><span class="inline-flex h-8 w-8 items-center justify-center rounded-chip bg-brand-100 text-[11px] font-bold text-brand-700" aria-hidden="true">{inisial(orang.name)}</span><span class="absolute -right-0.5 -bottom-0.5 h-2.5 w-2.5 rounded-full border-2 border-surface {orang.state==='aktif'?'bg-success':'bg-accent-400'}" aria-hidden="true"></span></span><span class="min-w-0"><span class="block truncate text-[13px] leading-tight font-semibold text-ink-800">{orang.name}</span><span class="block truncate text-[11px] leading-tight text-ink-500">{orang.label}</span></span></li>{/each}</ul><p class="shrink-0 border-t border-ink-100 px-4 py-3 text-[11px] leading-relaxed text-ink-600">Ingin menyapa seseorang secara langsung? Kontaknya ada di Jejaring anggota.</p></Card></aside>
</div>

<ForumModerationPanel open={panelModerasi} initialUserId={targetModerasi} onclose={()=>{panelModerasi=false;targetModerasi=''}} />

<style>
	:global(header[data-search-results-visible='false'] [aria-label='Hasil pencarian pesan']) { display: none; }
</style>
