<script>
	import { onMount, tick } from 'svelte';
	import { Avatar, Card, Icon, ICONS } from '$lib/components';
	import EmojiReactionPicker from '$lib/components/EmojiReactionPicker.svelte';
	import { forum } from '$lib/stores/forum.svelte.js';
	import { toast } from '$lib/stores/toast.svelte.js';
	import { formatTanggal, frasaHitung, inisial } from '$lib/utils/format.js';
	const AMBANG_GABUNG_MENIT=8, BATAS_KARAKTER=600;
	let draf=$state(''), wadahPesan=$state(null), kotakPesan=$state(null), menuPesanId=$state(''), pickerPesanId=$state(''), balasKe=$state(null), sorotId=$state(''), timerTutupMenu;
	const kanal=$derived(forum.channels.find(x=>x.slug===forum.activeSlug)??forum.channels[0]);
	const pesanTampil=$derived.by(()=>{const rows=forum.messages[forum.activeSlug]??[];return rows.map((pesan,index)=>{const before=rows[index-1],gap=before?(pesan.waktu-before.waktu)/60000:Infinity;return{...pesan,gabung:!pesan.balasan&&Boolean(before)&&before.penulis===pesan.penulis&&gap<AMBANG_GABUNG_MENIT}})});
	const dapatKirim=$derived(Boolean(kanal?.canPost&&draf.trim()&&!forum.sending));
	const jumlahAktif=$derived(forum.presence.filter(x=>x.state==='aktif').length);
	async function gulirKeBawah(){await tick();if(wadahPesan)wadahPesan.scrollTop=wadahPesan.scrollHeight}
	async function bukaKanal(slug){menuPesanId='';pickerPesanId='';balasKe=null;await forum.open(slug);await gulirKeBawah()}
	async function kirim(){const isi=draf.trim(),replyTo=balasKe?.id||'';if(!isi||!kanal?.canPost)return;draf='';try{await forum.send(isi,replyTo);balasKe=null;await gulirKeBawah()}catch(error){draf=isi;toast.error('Pesan belum terkirim',error instanceof Error?error.message:'Coba kirim kembali.')}}
	function tekanTombol(event){if(event.key!=='Enter'||event.shiftKey)return;event.preventDefault();void kirim()}
	async function reaksi(pesan,emoji){try{await forum.react(pesan,emoji)}catch(error){toast.error('Reaksi belum tersimpan',error instanceof Error?error.message:'Coba lagi.')}}
	async function pilihReaksi(pesan,emoji){pickerPesanId='';await reaksi(pesan,emoji)}
	function bukaMenuHover(id){if(timerTutupMenu)clearTimeout(timerTutupMenu);timerTutupMenu=undefined;if(!pickerPesanId)menuPesanId=id}
	function jadwalkanTutupMenu(id){if(timerTutupMenu)clearTimeout(timerTutupMenu);timerTutupMenu=setTimeout(()=>{if(menuPesanId===id&&pickerPesanId!==id)menuPesanId=''},300)}
	async function mulaiBalas(pesan){balasKe={id:pesan.id,penulis:pesan.penulis,isi:pesan.isi};menuPesanId='';pickerPesanId='';await tick();kotakPesan?.focus()}
	async function menujuPesan(id){let element=document.querySelector(`[data-forum-message="${id}"]`);if(!element){try{await forum.context(id);await tick();element=document.querySelector(`[data-forum-message="${id}"]`)}catch(error){toast.error('Pesan asal belum ditemukan',error instanceof Error?error.message:'Coba lagi.')}}if(element){element.scrollIntoView({behavior:'smooth',block:'center'});sorotId=id;setTimeout(()=>{if(sorotId===id)sorotId=''},2200)}}
	onMount(()=>{void forum.load().then(gulirKeBawah);return()=>{void forum.destroy()}});
</script>

<svelte:head><title>Forum Komunitas: PFriends</title></svelte:head>
<div class="mb-4"><p class="label-micro">Ruang percakapan PFriends</p><h1 class="mt-1 font-sans text-2xl font-bold tracking-[-0.02em] text-heading">Forum</h1><p class="mt-1.5 max-w-2xl text-sm leading-relaxed text-ink-600">Tempat alumni Sobat Bumi dan pelaku usaha PFpreneur saling menyapa, bertanya, dan berbagi kabar: dipisah per kanal supaya percakapan yang kamu cari tidak tenggelam.</p></div>
{#if forum.error}<div class="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900">{forum.error}</div>{/if}
<div class="grid gap-4 lg:h-[calc(100vh-11rem)] lg:min-h-[540px] lg:grid-cols-[15rem_minmax(0,1fr)] xl:grid-cols-[15rem_minmax(0,1fr)_14rem]">
	<nav aria-label="Daftar kanal forum" class="min-w-0">
		<div class="hidden h-full flex-col rounded-card border border-ink-100 bg-surface p-2 lg:flex"><p class="label-micro px-2 pt-2 pb-3">Kanal komunitas</p><ul class="min-h-0 flex-1 space-y-1 overflow-y-auto">{#each forum.channels as item (item.id)}<li><button type="button" aria-current={item.slug===forum.activeSlug?'true':undefined} class="flex min-h-11 w-full items-center gap-2 rounded-xl px-2.5 text-sm transition-colors {item.slug===forum.activeSlug?'bg-pertamina-navy-tint font-semibold text-pertamina-navy':'font-medium text-ink-600 hover:bg-ink-50 hover:text-ink-800'}" onclick={()=>bukaKanal(item.slug)}><span class="shrink-0 text-base leading-none opacity-70" aria-hidden="true">#</span><span class="min-w-0 flex-1 truncate text-left">{item.name}</span>{#if item.slug==='pengumuman'}<Icon path={ICONS.megaphone} size={14}/>{/if}</button></li>{/each}</ul><div class="mt-2 shrink-0 border-t border-ink-100 px-2.5 pt-3 pb-1"><p class="text-[11px] leading-relaxed text-ink-600">Kanal baru dibuka atas usulan chapter. Sampaikan di #tanya-jawab bila komunitasmu membutuhkan ruangnya sendiri.</p></div></div>
		<ul class="-mx-1 flex gap-2 overflow-x-auto px-1 pb-1 lg:hidden">{#each forum.channels as item (item.id)}<li class="shrink-0"><button type="button" aria-current={item.slug===forum.activeSlug?'true':undefined} class="inline-flex min-h-9 items-center rounded-chip border px-3 text-sm transition-colors {item.slug===forum.activeSlug?'border-pertamina-navy bg-pertamina-navy-tint font-semibold text-pertamina-navy':'border-ink-200 bg-surface font-medium text-ink-600'}" onclick={()=>bukaKanal(item.slug)}>#{item.name}</button></li>{/each}</ul>
	</nav>
	<section class="flex min-w-0 flex-col overflow-hidden rounded-card border border-ink-100 bg-surface" aria-label="Percakapan kanal {kanal?.name??''}">
		<header class="shrink-0 border-b border-ink-100 px-4 py-3"><h2 class="flex items-center gap-1.5 text-base font-bold text-heading"><span class="text-ink-400" aria-hidden="true">#</span>{kanal?.name??'Memuat kanal'}</h2><p class="mt-0.5 text-[13px] leading-relaxed text-ink-600">{kanal?.topic??''}</p></header>
		<div bind:this={wadahPesan} class="max-h-[52vh] min-h-0 flex-1 space-y-1 overflow-y-auto px-4 py-4 lg:max-h-none">
			{#if kanal}<div class="mb-4 rounded-xl bg-brand-50 px-3.5 py-3"><p class="text-[13px] leading-relaxed text-brand-700"><span class="font-semibold">Selamat datang di #{kanal.name}.</span> {kanal.note}</p></div>{/if}
			{#if kanal?.hasMore}<button type="button" class="mx-auto mb-3 block text-xs font-semibold text-brand-700" onclick={()=>forum.older()}>Muat pesan sebelumnya</button>{/if}
			{#if forum.loading&&pesanTampil.length===0}<p class="py-8 text-center text-sm text-ink-500">Memuat percakapan...</p>{:else if pesanTampil.length===0}<p class="py-8 text-center text-sm text-ink-500">Belum ada pesan di kanal ini.</p>{/if}
			{#each pesanTampil as pesan (pesan.id)}
				<article data-forum-message={pesan.id} class="group relative flex gap-3 rounded-xl px-1.5 py-1 transition-colors hover:bg-ink-50 {pesan.gabung?'':'mt-3'} {sorotId===pesan.id?'bg-brand-50 ring-1 ring-brand-200':''}">
					<div class="w-9 shrink-0 pt-0.5">{#if pesan.gabung}<span class="sr-only">{pesan.penulis}</span>{:else}<Avatar name={pesan.penulis} size="sm"/>{/if}</div>
					<div class="min-w-0 flex-1 pr-8">{#if !pesan.gabung}<p class="flex flex-wrap items-baseline gap-x-2 gap-y-0.5"><span class="text-sm font-bold {pesan.saya?'text-brand-700':'text-heading'}">{pesan.penulis}</span><span class="text-[11px] text-ink-500">{pesan.peran}</span><span class="numeric text-[11px] font-medium text-ink-500">{formatTanggal(pesan.waktu,'jam')}</span></p>{/if}{#if pesan.balasan}<button type="button" class="mt-1 block max-w-full border-l-2 border-ink-300 pl-2 text-left text-[11px] text-ink-500 hover:text-brand-700" onclick={()=>menujuPesan(pesan.balasan.id)}><span class="font-semibold">Membalas {pesan.balasan.penulis}</span><span class="block truncate">{pesan.balasan.isi}</span></button>{/if}<p class="mt-0.5 text-sm leading-relaxed break-words text-ink-700">{pesan.isi}</p>{#if pesan.reaksi.length}<ul class="mt-1.5 flex flex-wrap gap-1.5">{#each pesan.reaksi as item (item.emoji)}<li><button type="button" aria-pressed={item.dipilih} class="inline-flex items-center gap-1 rounded-chip border px-2 py-0.5 text-[11px] transition-colors {item.dipilih?'border-sky-400 bg-sky-100 font-semibold text-sky-800 ring-1 ring-sky-200':'border-ink-200 bg-ink-50 text-ink-700 hover:border-sky-300 hover:bg-sky-50'}" onclick={()=>reaksi(pesan,item.emoji)}><span aria-hidden="true">{item.emoji}</span><span class="numeric">{item.jumlah}</span></button></li>{/each}</ul>{/if}</div>
					<div class="absolute top-0.5 right-1 z-20 opacity-100 transition-opacity md:opacity-0 md:group-hover:opacity-100 md:group-focus-within:opacity-100" role="group" aria-label="Tindakan untuk pesan {pesan.penulis}" onmouseenter={()=>bukaMenuHover(pesan.id)} onmouseleave={()=>jadwalkanTutupMenu(pesan.id)}><button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-ink-200 bg-surface text-ink-600 shadow-sm hover:text-heading" aria-label="Tindakan pesan" aria-expanded={menuPesanId===pesan.id||pickerPesanId===pesan.id} onclick={()=>{pickerPesanId='';menuPesanId=menuPesanId===pesan.id?'':pesan.id}}><Icon path={ICONS.dots} size={17}/></button>{#if menuPesanId===pesan.id}<div class="absolute right-0 mt-1 w-40 rounded-xl border border-ink-200 bg-surface p-1 shadow-lg"><button type="button" class="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-ink-700 hover:bg-ink-50" onclick={()=>{menuPesanId='';pickerPesanId=pesan.id}}>Tambah reaksi</button><button type="button" class="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-ink-700 hover:bg-ink-50" onclick={()=>mulaiBalas(pesan)}>Balas</button></div>{/if}{#if pickerPesanId===pesan.id}<EmojiReactionPicker onselect={(emoji)=>pilihReaksi(pesan,emoji)} onclose={()=>pickerPesanId=''}/>{/if}</div>
				</article>
			{/each}
		</div>
		<div class="shrink-0 border-t border-ink-100 bg-surface p-3">{#if balasKe}<div class="mb-2 flex items-center gap-2 rounded-xl bg-ink-50 px-3 py-2"><p class="min-w-0 flex-1 text-xs text-ink-600"><span class="font-semibold text-ink-800">Membalas {balasKe.penulis}</span><span class="block truncate">{balasKe.isi}</span></p><button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-ink-500 hover:bg-surface hover:text-heading" aria-label="Batalkan balasan" onclick={()=>balasKe=null}><Icon path={ICONS.x} size={16}/></button></div>{/if}<form class="flex items-end gap-2 rounded-xl border border-ink-200 bg-canvas p-2 focus-within:border-brand-300" onsubmit={(event)=>{event.preventDefault();void kirim()}}><label class="sr-only" for="kotak-pesan">Tulis pesan di kanal {kanal?.name??''}</label><textarea bind:this={kotakPesan} id="kotak-pesan" rows="1" maxlength={BATAS_KARAKTER} bind:value={draf} onkeydown={tekanTombol} disabled={!kanal?.canPost} placeholder={kanal?.canPost?`Tulis pesan di #${kanal.name}…`:'Kanal ini hanya dapat ditulis oleh staf.'} class="max-h-32 min-h-11 flex-1 resize-none border-0 bg-transparent px-2 py-2 text-sm leading-relaxed text-ink-800 placeholder:text-ink-500 focus:ring-0 disabled:cursor-not-allowed disabled:bg-transparent"></textarea><button type="submit" disabled={!dapatKirim} class="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-pertamina-red-ink text-white transition-colors hover:bg-pertamina-red-dark disabled:bg-ink-200 disabled:text-ink-500" aria-label="Kirim pesan"><Icon path={ICONS.arrowRight} size={18}/></button></form><p class="mt-1.5 px-1 text-[11px] text-ink-500">{kanal?.canPost?'Enter mengirim · Shift+Enter membuat baris baru':'Hanya Admin dan Verifikator yang dapat mengirim di kanal ini'} · {frasaHitung(pesanTampil.length,'pesan')} di kanal ini</p></div>
	</section>
	<aside class="hidden min-w-0 xl:block" aria-label="Anggota yang sedang daring"><Card padding="none" class="flex h-full flex-col overflow-hidden"><p class="label-micro shrink-0 px-4 pt-4 pb-3">Daring · {jumlahAktif}</p><ul class="min-h-0 flex-1 space-y-1 overflow-y-auto px-2 pb-3">{#each forum.presence as orang (orang.id)}<li class="flex items-center gap-2.5 rounded-xl px-2 py-1.5"><span class="relative shrink-0"><span class="inline-flex h-8 w-8 items-center justify-center rounded-chip bg-brand-100 text-[11px] font-bold text-brand-700" aria-hidden="true">{inisial(orang.name)}</span><span class="absolute -right-0.5 -bottom-0.5 h-2.5 w-2.5 rounded-full border-2 border-surface {orang.state==='aktif'?'bg-success':'bg-accent-400'}" aria-hidden="true"></span></span><span class="min-w-0"><span class="block truncate text-[13px] leading-tight font-semibold text-ink-800">{orang.name}</span><span class="block truncate text-[11px] leading-tight text-ink-500">{orang.label}</span></span></li>{/each}</ul><p class="shrink-0 border-t border-ink-100 px-4 py-3 text-[11px] leading-relaxed text-ink-600">Ingin menyapa seseorang secara langsung? Kontaknya ada di Jejaring anggota.</p></Card></aside>
</div>
