import PocketBase from 'pocketbase';
import { buildSeed } from '../../src/lib/infrastructure/seed/seed-data.js';
import { SANDI_DEMO } from '../../src/lib/infrastructure/seed/accounts.js';
import { loadLocalEnv } from '../pocketbase/local-env.mjs';

await loadLocalEnv();
const url = process.env.VITE_PB_URL || 'http://127.0.0.1:8090';
const accounts = buildSeed().accounts;
const maintenance = new PocketBase(url);
await maintenance.collection('_superusers').authWithPassword(process.env.PB_SUPERUSER_EMAIL, process.env.PB_SUPERUSER_PASSWORD);
for (const row of await maintenance.collection('movements').getFullList({ filter: 'title ~ "Gerakan Integrasi"' })) await maintenance.collection('movements').delete(row.id);
const awardees = accounts.filter((item) => item.role === 'AWARDEE' && item.status === 'AKTIF').slice(0, 2);
const verifier = accounts.find((item) => item.role === 'VERIFIER' && item.status === 'AKTIF');
if (awardees.length < 2 || !verifier) throw new Error('Akun demo untuk pengujian Gerakan tidak lengkap.');
const login = async (account) => { const pb = new PocketBase(url); await pb.collection('users').authWithPassword(account.email, SANDI_DEMO); return pb; };
const leader = await login(awardees[0]); const participant = await login(awardees[1]); const reviewer = await login(verifier);
let checks = 0; const expect = (value, message) => { if (!value) throw new Error(message); checks++; };
const legacyProposal = await maintenance.collection('movements').getFirstListItem('status = "DIUSULKAN"');
expect(Boolean(legacyProposal.proposedBy && legacyProposal.leaderLegacyId && legacyProposal.leaderName), 'Usulan lama harus terhubung dengan akun pengusul dan pemimpin.');
const suffix = Date.now(); const startsAt = new Date(Date.now() + 86400000).toISOString(); const endsAt = new Date(Date.now() + 604800000).toISOString();
const movement = await leader.send('/api/pfriends/movements', { method: 'POST', body: { title: `Gerakan Integrasi ${suffix}`, category: 'LINGKUNGAN', objective: 'Menguji alur Gerakan dari usulan sampai laporan', description: 'Gerakan integrasi ini memastikan data usulan, partisipasi, dan laporan tersimpan sepenuhnya pada PocketBase.', region: 'Jakarta', startsAt, endsAt, targetParticipants: 12 } });
expect(movement.status === 'DIUSULKAN', 'Usulan harus berstatus DIUSULKAN.');
await reviewer.send(`/api/pfriends/verifier/movements/${movement.id}/decision`, { method: 'POST', body: { decision: 'APPROVE', note: 'Layak dijalankan', esgTags: [{ pillar: 'E', sdgGoal: 12 }] } });
await participant.send(`/api/pfriends/movements/${movement.id}/join`, { method: 'POST' });
const listed = await participant.send('/api/pfriends/movements'); const current = listed.items.find((item) => item.id === movement.id);
expect(current?.myParticipant?.role === 'PARTICIPANT', 'Peserta harus tercatat pada Gerakan.'); expect(current?.participantCount === 2, 'Pemimpin dan peserta harus masuk agregat.');
const form = new FormData(); form.set('activityDate', new Date().toISOString().slice(0, 10)); form.set('location', 'Jakarta'); form.set('participantCount', '8'); form.set('outcomeNote', 'Aksi integrasi menghasilkan dokumentasi kegiatan dan catatan hasil yang dapat diperiksa oleh Verifikator.'); form.set('evidenceFiles', new Blob([Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,0])], { type: 'image/png' }), 'bukti.png');
const report = await participant.send(`/api/pfriends/movements/${movement.id}/action-reports`, { method: 'POST', body: form }); expect(report.status === 'SUBMITTED', 'Laporan harus masuk antrean.');
await reviewer.send(`/api/pfriends/verifier/movement-reports/${report.id}/start-review`, { method: 'POST' }); const approved = await reviewer.send(`/api/pfriends/verifier/movement-reports/${report.id}/decision`, { method: 'POST', body: { decision: 'APPROVE', note: 'Bukti sesuai' } });
expect(approved.status === 'APPROVED', 'Laporan harus dapat disetujui.'); expect(approved.awardedPoints === 0, 'Peserta biasa tidak menerima poin pemimpin.');
await reviewer.send(`/api/pfriends/verifier/movements/${movement.id}/complete`, { method: 'POST' }); const finalList = await reviewer.send('/api/pfriends/movements'); expect(finalList.items.find((item) => item.id === movement.id)?.status === 'SELESAI', 'Gerakan harus dapat diselesaikan setelah laporan disetujui.');
await maintenance.collection('movements').delete(movement.id);
console.log(`Workflow Gerakan PocketBase: ${checks} pemeriksaan lulus.`);
