<script>
	import { page } from '$app/state';
	import { PageHeader, Card, StatusBadge, Button, ICONS } from '$lib/components';
	import { aturanSkor } from '$lib/domain/constants/scoring-table.js';
	import { activitySubmissions, SUBMISSION_STATUS_META } from '$lib/stores/activity-submissions.svelte.js';
	import { toast, ToastType } from '$lib/stores/toast.svelte.js';
	let note = $state(''); let started = false;
	$effect(() => { if (!started && page.params.id) { started = true; void activitySubmissions.detail(page.params.id); } });
	async function decide(decision) { try { await activitySubmissions.review(page.params.id, decision, note); toast.push({ type: ToastType.SUCCESS, title: decision === 'APPROVE' ? 'Bukti disetujui' : 'Revisi diminta', message: decision === 'APPROVE' ? 'Poin telah dibukukan secara otomatis.' : 'Catatan dapat dilihat Awardee.' }); note = ''; } catch {} }
</script>
<svelte:head><title>Detail Bukti Keaktifan · Verifikator PFfriends</title></svelte:head>
<PageHeader eyebrow="Verifikasi bukti" title={activitySubmissions.selected?.title ?? 'Memuat pengajuan…'} description="Periksa konteks aktivitas dan seluruh lampiran sebelum mengambil keputusan." />
{#if activitySubmissions.selected}{@const item = activitySubmissions.selected}{@const rule = aturanSkor(item.activityType)}
	<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
		<div class="grid gap-5"><Card><div class="flex flex-wrap items-center gap-2"><StatusBadge label={SUBMISSION_STATUS_META[item.status]?.label} color={SUBMISSION_STATUS_META[item.status]?.color} withDot /><span class="text-sm text-ink-500">{rule.label} · {rule.points} poin</span></div><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt class="text-xs text-ink-500">Awardee</dt><dd class="font-semibold">{item.expand?.owner?.displayName ?? item.awardeeId}</dd></div><div><dt class="text-xs text-ink-500">Tanggal aktivitas</dt><dd>{String(item.activityDate).slice(0,10)}</dd></div></dl><p class="mt-5 whitespace-pre-wrap text-sm leading-6 text-ink-700">{item.description}</p>{#if item.externalUrl}<a class="mt-4 inline-block text-sm font-semibold text-info underline" href={item.externalUrl} target="_blank" rel="noreferrer">Buka tautan pendukung</a>{/if}</Card>
		<Card><h2 class="font-semibold text-heading">Lampiran bukti</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">{#each item.evidenceFiles as file}{@const url = activitySubmissions.fileUrl(item,file)}{#if /\.pdf$/i.test(file)}<a class="rounded-xl border border-ink-200 p-4 text-sm font-semibold text-info" href={url} target="_blank" rel="noreferrer">Buka PDF · {file}</a>{:else}<a href={url} target="_blank" rel="noreferrer"><img src={url} alt={`Bukti ${file}`} class="aspect-video w-full rounded-xl border border-ink-200 object-cover" /></a>{/if}{/each}</div></Card></div>
		<aside><Card><h2 class="font-semibold text-heading">Keputusan</h2>{#if item.status === 'SUBMITTED'}<label class="mt-4 grid gap-1.5 text-sm font-medium">Catatan<textarea bind:value={note} rows="5" maxlength="2000" class="rounded-xl border border-ink-200 p-3" placeholder="Wajib saat meminta revisi; opsional saat menyetujui."></textarea></label><div class="mt-4 grid gap-2"><Button loading={activitySubmissions.working} variant="success" onclick={() => decide('APPROVE')}>Setujui · +{rule.points} poin</Button><Button loading={activitySubmissions.working} variant="outline" disabled={note.trim().length < 5} onclick={() => decide('REQUEST_REVISION')}>Minta revisi</Button></div>{:else}<p class="mt-3 text-sm text-ink-600">Pengajuan ini sudah diputuskan.</p>{/if}{#if item.reviewNote}<p class="mt-4 rounded-lg bg-ink-50 p-3 text-sm">{item.reviewNote}</p>{/if}</Card>
		{#if activitySubmissions.reviews.length}<Card className="mt-4"><h2 class="font-semibold text-heading">Riwayat review</h2><ol class="mt-3 grid gap-3">{#each activitySubmissions.reviews as review}<li class="border-l-2 border-ink-200 pl-3 text-sm"><strong>{review.decision === 'APPROVE' ? 'Disetujui' : 'Diminta revisi'}</strong><br/><span class="text-ink-500">{review.expand?.reviewer?.displayName} · {String(review.decidedAt).slice(0,16).replace('T',' ')}</span>{#if review.note}<p class="mt-1">{review.note}</p>{/if}</li>{/each}</ol></Card>{/if}</aside>
	</div>
{/if}
