<script>
	import { onMount } from 'svelte';
	import { listMovements, proposeMovement, joinMovement, submitMovementReport } from '$lib/infrastructure/pocketbase/movements.js';
	let items = $state([]), loading = $state(true), error = $state(''), showProposal = $state(false), reportFor = $state(null);
	let proposal = $state({ title: '', category: 'LINGKUNGAN', objective: '', description: '', region: '', startsAt: '', endsAt: '', targetParticipants: 10 });
	async function load() { loading = true; error = ''; try { items = await listMovements(); } catch (e) { error = e.message; } finally { loading = false; } }
	async function propose() { try { await proposeMovement({ ...proposal, targetParticipants: Number(proposal.targetParticipants), startsAt: new Date(proposal.startsAt).toISOString(), endsAt: new Date(proposal.endsAt).toISOString() }); showProposal = false; await load(); } catch (e) { error = e.message; } }
	async function join(id) { try { await joinMovement(id); await load(); } catch (e) { error = e.message; } }
	async function report(event) { try { await submitMovementReport(reportFor.id, new FormData(event.currentTarget)); reportFor = null; await load(); } catch (e) { error = e.message; } }
	onMount(load);
</script>
<svelte:head><title>Gerakan Awardee | PFriends</title></svelte:head>
<section class="space-y-6">
	<header class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="text-sm font-semibold text-emerald-200">Aksi bersama Awardee</p><h1 class="mt-1 text-3xl font-bold">Gerakan</h1><p class="mt-2 max-w-3xl text-emerald-100">Ajukan aksi, bergabung sebagai peserta, lalu kirim laporan hasil dan bukti lapangan. Verifikator memeriksa usulan serta laporan. Poin 50 diberikan satu kali kepada pemimpin setelah laporan pemimpin disetujui.</p><button class="mt-5 rounded-lg bg-white px-4 py-2 font-semibold text-emerald-950" onclick={() => showProposal = !showProposal}>Ajukan Gerakan</button></header>
	{#if error}<p class="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>{/if}
	{#if showProposal}<form class="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-2" onsubmit={(e) => { e.preventDefault(); propose(); }}><h2 class="text-xl font-bold md:col-span-2">Usulan baru</h2><label>Judul<input class="mt-1 w-full rounded-lg border p-2" required minlength="10" bind:value={proposal.title}></label><label>Kategori<select class="mt-1 w-full rounded-lg border p-2" bind:value={proposal.category}><option value="LINGKUNGAN">Lingkungan</option><option value="EDUKASI">Edukasi</option><option value="EKONOMI">Ekonomi</option></select></label><label class="md:col-span-2">Tujuan<input class="mt-1 w-full rounded-lg border p-2" required minlength="20" bind:value={proposal.objective}></label><label class="md:col-span-2">Deskripsi<textarea class="mt-1 w-full rounded-lg border p-2" required minlength="40" bind:value={proposal.description}></textarea></label><label>Wilayah<input class="mt-1 w-full rounded-lg border p-2" required bind:value={proposal.region}></label><label>Target peserta<input class="mt-1 w-full rounded-lg border p-2" type="number" min="1" bind:value={proposal.targetParticipants}></label><label>Mulai<input class="mt-1 w-full rounded-lg border p-2" type="datetime-local" required bind:value={proposal.startsAt}></label><label>Selesai<input class="mt-1 w-full rounded-lg border p-2" type="datetime-local" required bind:value={proposal.endsAt}></label><button class="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white md:col-span-2">Kirim ke Verifikator</button></form>{/if}
	{#if loading}<p>Memuat data Gerakan...</p>{:else if !items.length}<p class="rounded-xl border bg-white p-5">Belum ada Gerakan yang dapat ditampilkan.</p>{:else}<div class="grid gap-5 lg:grid-cols-2">{#each items as movement}<article class="rounded-2xl border bg-white p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-emerald-700">{movement.category}</p><h2 class="text-xl font-bold">{movement.title}</h2></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{movement.status}</span></div><p class="mt-3 text-slate-700">{movement.description}</p><p class="mt-4 text-sm"><b>{movement.region}</b> • {movement.participantCount} peserta • {movement.approvedReportCount} laporan disetujui</p><p class="mt-1 text-sm">Pemimpin: {movement.leaderName}</p>{#if movement.reviewNote}<p class="mt-4 rounded-lg bg-amber-50 p-3 text-sm">Catatan Verifikator: {movement.reviewNote}</p>{/if}<div class="mt-5 flex flex-wrap gap-2">{#if movement.status === 'BERJALAN' && !movement.myParticipant}<button class="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white" onclick={() => join(movement.id)}>Gabung</button>{/if}{#if movement.status === 'BERJALAN' && movement.myParticipant}<button class="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white" onclick={() => reportFor = movement}>Kirim laporan aksi</button><span class="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800">Peran {movement.myParticipant.role}</span>{/if}</div>{#if movement.reports?.length}<div class="mt-4 border-t pt-4"><h3 class="font-bold">Laporan saya</h3>{#each movement.reports as report}<p class="mt-2 text-sm">{report.activityDate.slice(0,10)} • {report.status}{#if report.awardedPoints} • {report.awardedPoints} poin{/if}</p>{/each}</div>{/if}</article>{/each}</div>{/if}
</section>
{#if reportFor}<div class="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form class="w-full max-w-xl space-y-4 rounded-2xl bg-white p-6" onsubmit={(e) => { e.preventDefault(); report(e); }}><h2 class="text-xl font-bold">Laporan {reportFor.title}</h2><label class="block">Tanggal aksi<input class="mt-1 w-full rounded-lg border p-2" name="activityDate" type="date" required></label><label class="block">Lokasi<input class="mt-1 w-full rounded-lg border p-2" name="location" required></label><label class="block">Jumlah peserta<input class="mt-1 w-full rounded-lg border p-2" name="participantCount" type="number" min="1" required></label><label class="block">Hasil aksi<textarea class="mt-1 w-full rounded-lg border p-2" name="outcomeNote" minlength="40" required></textarea></label><label class="block">Bukti foto atau PDF<input class="mt-1 w-full rounded-lg border p-2" name="evidenceFiles" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required multiple></label><div class="flex gap-2"><button class="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Kirim laporan</button><button type="button" class="rounded-lg border px-4 py-2" onclick={() => reportFor = null}>Batal</button></div></form></div>{/if}
