routerAdd('GET','/api/pfriends/profile/me',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e);return e.json(200,u.profileDto(e.app,awardee));},$apis.requireAuth('users'));

routerAdd('PATCH','/api/pfriends/profile/me',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e),before=u.snapshot(awardee),body=e.requestInfo().body||{},locked=['fullName','email','community','programPillar','chapterId','university','graduationYear'];if(locked.some(key=>body[key]!==undefined))throw new BadRequestError('Data identitas terverifikasi tidak dapat diubah dari Profil Saya.');const data=u.validateProfile(e.app,awardee,body);let avatars=[];try{avatars=e.findUploadedFiles('avatar')||[];}catch(_){}u.applyProfile(awardee,data);if(String(body.removeAvatar||'')==='true')awardee.set('avatar',null);else if(avatars.length)awardee.set('avatar',avatars[0]);e.app.save(awardee);const after=u.snapshot(awardee);u.audit(e.app,awardee,e.auth,'PROFILE_UPDATE','',before,after);const result=u.profileDto(e.app,awardee);return e.json(200,{...result.profile,...result});},$apis.requireAuth('users'));

routerAdd('POST','/api/pfriends/profile/consents/{type}/grant',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e),type=e.request.pathValue('type');let result;e.app.runInTransaction(tx=>{const row=u.appendConsent(tx,tx.findRecordById('awardees',awardee.id),e.auth,type,'GRANTED');result=u.consentDto(row);});return e.json(201,result);},$apis.requireAuth('users'));

routerAdd('POST','/api/pfriends/profile/consents/{type}/revoke',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e),type=e.request.pathValue('type');let result,cascade={withdrawn:0,blocked:0};e.app.runInTransaction(tx=>{const current=tx.findRecordById('awardees',awardee.id),row=u.appendConsent(tx,current,e.auth,type,'REVOKED');result=u.consentDto(row);if(type==='PUBLIKASI_CERITA')cascade=u.cascadeStoryConsent(tx,current,e.auth);});return e.json(200,{consent:result,...cascade});},$apis.requireAuth('users'));

routerAdd('POST','/api/pfriends/profile/products',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e);if(awardee.getString('community')!=='WOMENPRENEUR')throw new ForbiddenError('Etalase hanya tersedia untuk Womenpreneur.');if(u.products(e.app,awardee).length>=5)throw new BadRequestError('Etalase maksimal memuat lima produk.');const body=e.requestInfo().body||{},name=String(body.name||'').trim(),category=String(body.category||'').trim(),description=String(body.description||'').trim(),files=e.findUploadedFiles('image')||[];if(name.length<2||category.length<2)throw new BadRequestError('Nama dan kategori produk wajib diisi.');if(description.length>1200)throw new BadRequestError('Deskripsi produk maksimal 1200 karakter.');if(files.length!==1)throw new BadRequestError('Satu foto produk wajib diunggah.');const now=new Date().toISOString(),row=new Record(e.app.findCollectionByNameOrId('business_products'));row.set('awardee',awardee.id);row.set('name',name);row.set('category',category);row.set('description',description);row.set('image',files[0]);row.set('createdAt',now);row.set('updatedAt',now);e.app.save(row);u.audit(e.app,awardee,e.auth,'PRODUCT_CREATE',row.id,null,u.productDto(row));return e.json(201,u.productDto(row));},$apis.requireAuth('users'));

routerAdd('PATCH','/api/pfriends/profile/products/{id}',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e),row=e.app.findRecordById('business_products',e.request.pathValue('id'));if(row.getString('awardee')!==awardee.id)throw new ForbiddenError('Produk ini bukan milik Anda.');const before=u.productDto(row),body=e.requestInfo().body||{},files=e.findUploadedFiles('image')||[];if(body.name!==undefined)row.set('name',String(body.name).trim());if(body.category!==undefined)row.set('category',String(body.category).trim());if(body.description!==undefined)row.set('description',String(body.description).trim());if(row.getString('name').length<2||row.getString('category').length<2||row.getString('description').length>1200)throw new BadRequestError('Data produk belum memenuhi ketentuan.');if(files.length)row.set('image',files[0]);row.set('updatedAt',new Date().toISOString());e.app.save(row);u.audit(e.app,awardee,e.auth,'PRODUCT_UPDATE',row.id,before,u.productDto(row));return e.json(200,u.productDto(row));},$apis.requireAuth('users'));

routerAdd('DELETE','/api/pfriends/profile/products/{id}',(e)=>{const u=require(`${__hooks}/awardee-profile-utils.js`),awardee=u.requireAwardee(e),row=e.app.findRecordById('business_products',e.request.pathValue('id'));if(row.getString('awardee')!==awardee.id)throw new ForbiddenError('Produk ini bukan milik Anda.');const before=u.productDto(row);u.audit(e.app,awardee,e.auth,'PRODUCT_DELETE',row.id,before,null);e.app.delete(row);return e.json(200,{deleted:true});},$apis.requireAuth('users'));
