const SCORE={BROADCAST_VIEW:1,CTA_REACT:2}; const CAP={BROADCAST_VIEW:3,CTA_REACT:5};
function auth(e,role){if(!e.auth||e.auth.getString('role')!==role||e.auth.getString('status')!=='AKTIF')throw new ForbiddenError(`Sesi ${role} aktif diperlukan.`)}
function dto(app,row,user){let read=false,cta=false,shares=0;if(user){const es=app.findRecordsByFilter('broadcast_engagements','broadcast={:b} && owner={:o}','',0,0,{b:row.id,o:user});read=es.some(x=>x.getString('type')==='BROADCAST_VIEW'&&x.getString('awardedAt'));cta=es.some(x=>x.getString('type')==='CTA_REACT'&&x.getString('awardedAt'));shares=es.filter(x=>x.getString('type')==='SHARE_PRIVATE').length}return{id:row.id,title:row.getString('title'),summary:row.getString('summary'),body:row.getString('body'),status:row.getString('status'),channel:row.getString('channel'),contentSource:row.getString('contentSource'),lightCta:row.getString('lightCta'),ctaLink:row.getString('ctaLink'),audience:row.getString('audience'),scheduledAt:row.getString('scheduledAt')||null,sentAt:row.getString('sentAt')||null,recipientCount:row.getInt('recipientCount'),read,ctaResponded:cta,privateShares:shares}}
function fill(r,body){const title=String(body.title||'').trim(),summary=String(body.summary||'').trim(),content=String(body.body||'').trim();if(title.length<5)throw new BadRequestError('Judul minimal 5 karakter.');if(summary.length<10)throw new BadRequestError('Ringkasan minimal 10 karakter.');if(content.length<20)throw new BadRequestError('Isi kabar minimal 20 karakter.');let schedule=String(body.scheduledAt||'').trim();if(schedule){const date=new Date(schedule);if(Number.isNaN(date.getTime()))throw new BadRequestError('Jadwal tidak valid.');schedule=date.toISOString()}r.set('title',title);r.set('summary',summary);r.set('body',content);r.set('channel',String(body.channel||'SEMUA'));r.set('contentSource',String(body.contentSource||''));r.set('lightCta',String(body.lightCta||''));r.set('ctaLink',String(body.ctaLink||''));r.set('audience',String(body.audience||'SEMUA'));r.set('scheduledAt',schedule);r.set('status',schedule?'TERJADWAL':'DRAF')}
function award(tx,e,broadcast,type,response,key){const awardee=tx.findFirstRecordByData('awardees','user',e.auth.id),now=new Date(),day=now.toISOString().slice(0,10);if(type!=='SHARE_PRIVATE'){try{const old=tx.findFirstRecordByFilter('broadcast_engagements','broadcast={:b} && owner={:o} && type={:t}',{b:broadcast.id,o:e.auth.id,t:type});if(old.getString('awardedAt'))return old}catch(_){}}if(type==='CTA_REACT'&&String(response||'').trim().length<20)throw new BadRequestError('Tanggapan minimal 20 karakter.');if(type==='BROADCAST_VIEW'){let started;try{started=tx.findFirstRecordByFilter('broadcast_engagements','broadcast={:b} && owner={:o} && type="BROADCAST_VIEW"',{b:broadcast.id,o:e.auth.id})}catch(_){throw new BadRequestError('Mulai membaca kabar terlebih dahulu.')}if(now-new Date(started.getString('startedAt'))<15000)throw new BadRequestError('Kabar perlu dibaca minimal 15 detik.')}const count=tx.findRecordsByFilter('verified_point_activities','awardeeId={:a} && activityType={:t} && occurredAt>={:s} && occurredAt<={:z}','',0,0,{a:awardee.getString('legacyId'),t:type,s:day+' 00:00:00.000Z',z:day+' 23:59:59.999Z'}).length;let row=null;if(type!=='SHARE_PRIVATE')try{row=tx.findFirstRecordByFilter('broadcast_engagements','broadcast={:b} && owner={:o} && type={:t}',{b:broadcast.id,o:e.auth.id,t:type})}catch(_){}if(!row)row=new Record(tx.findCollectionByNameOrId('broadcast_engagements'));row.set('broadcast',broadcast.id);row.set('owner',e.auth.id);row.set('awardeeId',awardee.getString('legacyId'));row.set('type',type);row.set('response',String(response||'').trim());row.set('requestKey',key||'');row.set('awardedAt',now.toISOString());row.set('points',count>=CAP[type]?0:SCORE[type]);tx.save(row);const ledger=new Record(tx.findCollectionByNameOrId('verified_point_activities'));ledger.set('user',e.auth.id);ledger.set('source','ENGAGEMENT');ledger.set('broadcast',broadcast.id);ledger.set('broadcastEngagement',row.id);ledger.set('awardeeId',awardee.getString('legacyId'));ledger.set('activityType',type);ledger.set('points',row.getInt('points'));ledger.set('capReason',row.getInt('points')?'':'DAILY_CAP');ledger.set('occurredAt',now.toISOString());ledger.set('awardedAt',now.toISOString());ledger.set('status','AWARDED');tx.save(ledger);return row}
function awardTraced(tx,e,broadcast,type,response,key){
	let stage='profil Awardee';
	try {
		const awardee=tx.findFirstRecordByData('awardees','user',e.auth.id),now=new Date(),day=now.toISOString().slice(0,10);
		stage='cek duplikat'; let row=null;
		if(type!=='SHARE_PRIVATE')try{row=tx.findFirstRecordByFilter('broadcast_engagements','broadcast={:b} && owner={:o} && type={:t}',{b:broadcast.id,o:e.auth.id,t:type})}catch(_){}
		if(row&&row.getString('awardedAt'))return row;
		if(type==='CTA_REACT'&&String(response||'').trim().length<20)throw new Error('Tanggapan minimal 20 karakter.');
		if(type==='BROADCAST_VIEW'){
			stage='validasi waktu baca'; if(!row)throw new Error('Mulai membaca kabar terlebih dahulu.');
			if(now-new Date(row.getString('startedAt'))<15000)throw new Error('Kabar perlu dibaca minimal 15 detik.');
		}
		stage='hitung batas harian'; const count=tx.findRecordsByFilter('verified_point_activities','awardeeId={:a} && activityType={:t} && occurredAt>={:s} && occurredAt<={:z}','',0,0,{a:awardee.getString('legacyId'),t:type,s:day+' 00:00:00.000Z',z:day+' 23:59:59.999Z'}).length;
		stage='simpan engagement'; if(!row)row=new Record(tx.findCollectionByNameOrId('broadcast_engagements')); row.set('broadcast',broadcast.id);row.set('owner',e.auth.id);row.set('awardeeId',awardee.getString('legacyId'));row.set('type',type);row.set('response',String(response||'').trim());row.set('requestKey',key||'');row.set('awardedAt',now.toISOString());row.set('points',count>=CAP[type]?0:SCORE[type]);tx.save(row);
		stage='simpan ledger'; const ledger=new Record(tx.findCollectionByNameOrId('verified_point_activities'));ledger.set('user',e.auth.id);ledger.set('source','ENGAGEMENT');ledger.set('broadcast',broadcast.id);ledger.set('broadcastEngagement',row.id);ledger.set('awardeeId',awardee.getString('legacyId'));ledger.set('activityType',type);ledger.set('points',row.getInt('points'));ledger.set('capReason',row.getInt('points')?'':'DAILY_CAP');ledger.set('occurredAt',now.toISOString());ledger.set('awardedAt',now.toISOString());ledger.set('status','AWARDED');tx.save(ledger);return row;
	} catch(error) { throw new Error(`${stage}: ${String(error)}`); }
}
module.exports={SCORE,auth,dto,fill,award:awardTraced};
