const EMOJIS=require(`${__hooks}/forum-emoji-allowlist.js`);
function auth(e){if(!e.auth||e.auth.getString('status')!=='AKTIF'||!['AWARDEE','VERIFIER','ADMIN'].includes(e.auth.getString('role')))throw new ForbiddenError('Sesi pengguna aktif diperlukan.');return e.auth}
function awardee(app,user){if(user.getString('role')!=='AWARDEE')return null;try{return app.findFirstRecordByData('awardees','user',user.id)}catch(_){return null}}
function canRead(app,user,channel){if(!channel.getBool('active'))return false;if(user.getString('role')!=='AWARDEE')return true;const community=channel.getString('community');if(!community)return true;const profile=awardee(app,user);return Boolean(profile&&profile.getString('status')==='AKTIF'&&profile.getString('community')===community)}
function canWrite(app,user,channel){if(!canRead(app,user,channel))return false;if(user.getString('role')!=='AWARDEE')return true;return !channel.getBool('staffOnlyWrite')}
function identity(app,user){if(user.getString('role')!=='AWARDEE')return{name:user.getString('displayName'),label:user.getString('role')==='ADMIN'?'Admin Pertamina Foundation':'Verifikator PFriends'};const profile=awardee(app,user);if(!profile)return{name:user.getString('displayName'),label:'Awardee PFriends'};return{name:profile.getString('fullName'),label:profile.getString('community')==='SOBI'?`SOBI · ${profile.getString('chapterId')}`:`Womenpreneur · ${profile.getString('businessName')||profile.getString('city')}`}}
function reactions(app,message,userId){const rows=app.findRecordsByFilter('forum_reactions','message={:m}','',0,0,{m:message.id}),counts={};for(const row of rows){const emoji=row.getString('emoji');if(!counts[emoji])counts[emoji]={emoji,count:0,selected:false};counts[emoji].count++;if(row.getString('user')===userId)counts[emoji].selected=true}return Object.values(counts).sort((a,b)=>b.count-a.count||a.emoji.localeCompare(b.emoji))}
function replyDto(app,row){const id=row.getString('replyTo');if(!id)return null;try{const parent=app.findRecordById('forum_messages',id);return{id:parent.id,authorName:parent.getString('authorName'),content:parent.getString('content').slice(0,180)}}catch(_){return null}}
function messageDto(app,row,userId){const mine=row.getString('author')===userId,userRole=app.findRecordById('users',userId).getString('role'),authorKind=row.getString('authorKind');return{id:row.id,channelId:row.getString('channel'),authorId:row.getString('author'),authorKind,authorName:row.getString('authorName'),authorLabel:row.getString('authorLabel'),content:row.getString('content'),mine,canDelete:authorKind!=='SYSTEM'&&(mine||['ADMIN','VERIFIER'].includes(userRole)),createdAt:row.getString('sentAt'),reply:replyDto(app,row),reactions:reactions(app,row,userId)}}
function channelDto(app,row,user){return{id:row.id,slug:row.getString('slug'),name:row.getString('name'),topic:row.getString('topic'),note:row.getString('note'),community:row.getString('community'),canPost:canWrite(app,user,row)}}
function publish(app,topic,data){const message=new SubscriptionMessage({name:topic,data:JSON.stringify(data)});const clients=app.subscriptionsBroker().clients();for(const id in clients){if(clients[id].hasSubscription(topic))clients[id].send(message)}}
module.exports={EMOJIS,auth,canRead,canWrite,identity,messageDto,channelDto,publish};
