function movementSlug(value) { return String(value || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }

routerAdd('GET', '/api/pfriends/movements', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, ['AWARDEE','VERIFIER','ADMIN']);
	const role = e.auth.getString('role'); let filter = 'id != ""';
	if (role === 'AWARDEE') filter = '(status = "BERJALAN" || status = "SELESAI") || proposedBy = {:owner}';
	const rows = e.app.findRecordsByFilter('movements', filter, '-submittedAt', 0, 0, { owner: e.auth.id });
	return e.json(200, { items: rows.map((row) => utils.movementDto(e.app, row, e.auth)) });
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/movements', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'AWARDEE');
	const movementSlug = (value) => String(value || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
	const body = new DynamicModel({ title: '', category: '', objective: '', description: '', region: '', startsAt: '', endsAt: '', targetParticipants: 0 }); e.bindBody(body);
	const start = new Date(body.startsAt); const end = new Date(body.endsAt);
	if (String(body.title).trim().length < 10 || String(body.objective).trim().length < 20 || String(body.description).trim().length < 40 || !String(body.region).trim()) throw new BadRequestError('Judul, tujuan, deskripsi, dan wilayah wajib dilengkapi.');
	const categoryMap = { LINGKUNGAN: 'AKSI_LINGKUNGAN', EDUKASI: 'EDUKASI_MASYARAKAT', EKONOMI: 'PEMBERDAYAAN_EKONOMI' };
	if (!categoryMap[body.category]) throw new BadRequestError('Kategori Gerakan tidak dikenal.');
	body.category = categoryMap[body.category];
	if (isNaN(start.getTime()) || isNaN(end.getTime()) || end <= start) throw new BadRequestError('Rentang pelaksanaan tidak sah.');
	let result; e.app.runInTransaction((tx) => { const row = new Record(tx.findCollectionByNameOrId('movements')); const base = movementSlug(body.title) || `gerakan-${Date.now()}`; let slug = base; try { tx.findFirstRecordByData('movements', 'slug', slug); slug = `${base}-${Date.now().toString(36)}`; } catch (_) {} row.set('slug', slug); row.set('title', String(body.title).trim()); row.set('category', body.category); row.set('status', 'DIUSULKAN'); row.set('objective', String(body.objective).trim()); row.set('description', String(body.description).trim()); row.set('region', String(body.region).trim()); row.set('leaderLegacyId', e.auth.getString('awardeeId')); row.set('leaderName', e.auth.getString('displayName')); row.set('startsAt', start.toISOString()); row.set('endsAt', end.toISOString()); row.set('targetParticipants', Math.max(1, Number(body.targetParticipants) || 1)); row.set('proposedBy', e.auth.id); row.set('submittedAt', new Date().toISOString()); tx.save(row); utils.decision(tx, row, null, e.auth, 'SUBMIT', '', 'DIUSULKAN', ''); result = row; }); return e.json(201, result);
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/movements/{id}/join', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'AWARDEE'); let result;
	e.app.runInTransaction((tx) => { const movement = tx.findRecordById('movements', e.request.pathValue('id')); if (movement.getString('status') !== 'BERJALAN') throw new BadRequestError('Gerakan belum dapat diikuti.'); try { tx.findFirstRecordByFilter('movement_participants', 'movement = {:movement} && owner = {:owner}', { movement: movement.id, owner: e.auth.id }); throw new BadRequestError('Anda sudah terdaftar pada Gerakan ini.'); } catch (error) { if (error instanceof BadRequestError) throw error; } const row = new Record(tx.findCollectionByNameOrId('movement_participants')); row.set('movement', movement.id); row.set('owner', e.auth.id); row.set('awardeeId', e.auth.getString('awardeeId')); row.set('awardeeName', e.auth.getString('displayName')); row.set('role', 'PARTICIPANT'); row.set('status', 'ACTIVE'); row.set('joinedAt', new Date().toISOString()); tx.save(row); result = row; }); return e.json(201, result);
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/movements/{id}/resubmit', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'AWARDEE');
	const body = new DynamicModel({ title: '', category: '', objective: '', description: '', region: '', startsAt: '', endsAt: '', targetParticipants: 0 }); e.bindBody(body);
	const movement = e.app.findRecordById('movements', e.request.pathValue('id'));
	if (movement.getString('proposedBy') !== e.auth.id) throw new ForbiddenError('Hanya pengusul yang dapat memperbaiki Gerakan ini.');
	if (movement.getString('status') !== 'PERLU_REVISI') throw new BadRequestError('Usulan tidak sedang menunggu perbaikan.');
	const start = new Date(body.startsAt); const end = new Date(body.endsAt);
	if (String(body.title).trim().length < 10 || String(body.objective).trim().length < 20 || String(body.description).trim().length < 40 || !String(body.region).trim()) throw new BadRequestError('Judul, tujuan, deskripsi, dan wilayah wajib dilengkapi.');
	const categoryMap = { LINGKUNGAN: 'AKSI_LINGKUNGAN', EDUKASI: 'EDUKASI_MASYARAKAT', EKONOMI: 'PEMBERDAYAAN_EKONOMI', AKSI_LINGKUNGAN: 'AKSI_LINGKUNGAN', EDUKASI_MASYARAKAT: 'EDUKASI_MASYARAKAT', PEMBERDAYAAN_EKONOMI: 'PEMBERDAYAAN_EKONOMI' };
	if (!categoryMap[body.category]) throw new BadRequestError('Kategori Gerakan tidak dikenal.');
	if (isNaN(start.getTime()) || isNaN(end.getTime()) || end <= start) throw new BadRequestError('Rentang pelaksanaan tidak sah.');
	let result; e.app.runInTransaction((tx) => { const row = tx.findRecordById('movements', movement.id); row.set('title', String(body.title).trim()); row.set('category', categoryMap[body.category]); row.set('objective', String(body.objective).trim()); row.set('description', String(body.description).trim()); row.set('region', String(body.region).trim()); row.set('startsAt', start.toISOString()); row.set('endsAt', end.toISOString()); row.set('targetParticipants', Math.max(1, Number(body.targetParticipants) || 1)); row.set('status', 'DIUSULKAN'); row.set('revisionCount', row.getInt('revisionCount') + 1); row.set('submittedAt', new Date().toISOString()); row.set('reviewedBy', ''); row.set('reviewedAt', ''); row.set('reviewNote', ''); tx.save(row); utils.decision(tx, row, null, e.auth, 'RESUBMIT', 'PERLU_REVISI', 'DIUSULKAN', ''); result = row; });
	return e.json(200, utils.movementDto(e.app, result, e.auth));
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/movements/{id}/reports', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'AWARDEE'); let result;
	e.app.runInTransaction((tx) => { const movement = tx.findRecordById('movements', e.request.pathValue('id')); if (movement.getString('status') !== 'BERJALAN') throw new BadRequestError('Laporan hanya dapat dikirim untuk Gerakan yang berjalan.'); const participant = tx.findFirstRecordByFilter('movement_participants', 'movement = {:movement} && owner = {:owner} && status = "ACTIVE"', { movement: movement.id, owner: e.auth.id }); const row = new Record(tx.findCollectionByNameOrId('movement_reports')); const form = new RecordUpsertForm(tx, row); form.loadRequest(e.request); form.set('movement', movement.id); form.set('participant', participant.id); form.set('owner', e.auth.id); form.set('awardeeId', e.auth.getString('awardeeId')); form.set('awardeeName', e.auth.getString('displayName')); form.set('role', participant.getString('role')); form.set('status', 'SUBMITTED'); form.set('submittedAt', new Date().toISOString()); form.submit(); if (!row.getString('activityDate') || !row.getString('location') || row.getInt('participantCount') < 1 || row.getString('outcomeNote').trim().length < 40 || row.getStringSlice('evidenceFiles').length < 1) throw new BadRequestError('Tanggal, lokasi, jumlah peserta, catatan hasil, dan minimal satu bukti wajib diisi.'); utils.decision(tx, movement, row, e.auth, 'SUBMIT', '', 'SUBMITTED', ''); result = row; }); return e.json(201, utils.reportDto(result));
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/movements/{id}/action-reports', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'AWARDEE');
	const data = e.requestInfo().body || {}; const files = e.findUploadedFiles('evidenceFiles'); let result;
	if (!data.activityDate || !String(data.location || '').trim() || Number(data.participantCount) < 1 || String(data.outcomeNote || '').trim().length < 40 || files.length < 1) throw new BadRequestError('Tanggal, lokasi, jumlah peserta, catatan hasil, dan minimal satu bukti wajib diisi.');
	e.app.runInTransaction((tx) => { const movement = tx.findRecordById('movements', e.request.pathValue('id')); if (movement.getString('status') !== 'BERJALAN') throw new BadRequestError('Laporan hanya dapat dikirim untuk Gerakan yang berjalan.'); const participant = tx.findFirstRecordByFilter('movement_participants', 'movement = {:movement} && owner = {:owner} && status = "ACTIVE"', { movement: movement.id, owner: e.auth.id }); const row = new Record(tx.findCollectionByNameOrId('movement_reports')); row.set('movement', movement.id); row.set('participant', participant.id); row.set('owner', e.auth.id); row.set('awardeeId', e.auth.getString('awardeeId')); row.set('awardeeName', e.auth.getString('displayName')); row.set('role', participant.getString('role')); row.set('activityDate', data.activityDate); row.set('location', String(data.location).trim()); row.set('participantCount', Number(data.participantCount)); row.set('outcomeNote', String(data.outcomeNote).trim()); row.set('evidenceFiles', files); row.set('status', 'SUBMITTED'); row.set('submittedAt', new Date().toISOString()); tx.save(row); utils.decision(tx, movement, row, e.auth, 'SUBMIT', '', 'SUBMITTED', ''); result = row; });
	return e.json(201, utils.reportDto(result));
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/movement-reports/{id}/resubmit', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'AWARDEE');
	const data = e.requestInfo().body || {}; let files = []; try { files = e.findUploadedFiles('evidenceFiles') || []; } catch (_) {}
	const original = e.app.findRecordById('movement_reports', e.request.pathValue('id'));
	if (original.getString('owner') !== e.auth.id) throw new ForbiddenError('Hanya pemilik laporan yang dapat mengirim perbaikan.');
	if (original.getString('status') !== 'NEEDS_REVISION') throw new BadRequestError('Laporan tidak sedang menunggu perbaikan.');
	if (!data.activityDate || !String(data.location || '').trim() || Number(data.participantCount) < 1 || String(data.outcomeNote || '').trim().length < 40) throw new BadRequestError('Tanggal, lokasi, jumlah peserta, dan catatan hasil wajib diisi.');
	if (!files.length && original.getStringSlice('evidenceFiles').length < 1) throw new BadRequestError('Minimal satu bukti wajib tersedia.');
	let result; try { e.app.runInTransaction((tx) => { const row = tx.findRecordById('movement_reports', original.id); const movement = tx.findRecordById('movements', row.getString('movement')); row.set('activityDate', data.activityDate); row.set('location', String(data.location).trim()); row.set('participantCount', Number(data.participantCount)); row.set('outcomeNote', String(data.outcomeNote).trim()); if (files.length) row.set('evidenceFiles', files); row.set('status', 'SUBMITTED'); row.set('revisionCount', row.getInt('revisionCount') + 1); row.set('submittedAt', new Date().toISOString()); row.set('reviewer', ''); row.set('reviewStartedAt', ''); row.set('reviewedAt', ''); row.set('reviewNote', ''); tx.save(row); utils.decision(tx, movement, row, e.auth, 'RESUBMIT', 'NEEDS_REVISION', 'SUBMITTED', ''); result = row; }); } catch (error) { throw new BadRequestError(`Pengajuan ulang laporan gagal: ${error.message || error}`); }
	return e.json(200, utils.reportDto(result));
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/verifier/movements/{id}/decision', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'VERIFIER'); const body = new DynamicModel({ decision: '', note: '', esgTags: [] }); e.bindBody(body); if (!['APPROVE','REQUEST_REVISION','REJECT'].includes(body.decision)) throw new BadRequestError('Keputusan tidak dikenal.'); if (body.decision !== 'APPROVE' && String(body.note).trim().length < 5) throw new BadRequestError('Catatan keputusan minimal 5 karakter.');
	if (body.decision === 'APPROVE') { const target = e.app.findRecordById('movements', e.request.pathValue('id')); if (!target.getString('proposedBy')) { try { let awardee = null; if (target.getString('leaderLegacyId')) awardee = e.app.findFirstRecordByData('awardees', 'legacyId', target.getString('leaderLegacyId')); else awardee = e.app.findRecordsByFilter('awardees', 'status = "AKTIF" && user != ""', 'fullName', 1, 0)[0]; if (!awardee || !awardee.getString('user')) throw new Error('Akun pemimpin kosong'); target.set('proposedBy', awardee.getString('user')); target.set('leaderLegacyId', awardee.getString('legacyId')); target.set('leaderName', awardee.getString('fullName')); e.app.save(target); } catch (_) { throw new BadRequestError('Akun pengusul Gerakan lama tidak ditemukan. Hubungkan data pemimpin sebelum menyetujui usulan.'); } } }
	let result; e.app.runInTransaction((tx) => { const movement = tx.findRecordById('movements', e.request.pathValue('id')); if (!['DIUSULKAN','PERLU_REVISI'].includes(movement.getString('status'))) throw new BadRequestError('Usulan tidak lagi menunggu keputusan.'); if (body.decision === 'APPROVE' && (!Array.isArray(body.esgTags) || body.esgTags.length < 1)) throw new BadRequestError('Minimal satu tag ESG atau SDG wajib ditetapkan.'); const before = movement.getString('status'); const after = body.decision === 'APPROVE' ? 'BERJALAN' : body.decision === 'REJECT' ? 'DITOLAK' : 'PERLU_REVISI'; const now = new Date().toISOString(); movement.set('status', after); movement.set('reviewedBy', e.auth.id); movement.set('reviewedAt', now); movement.set('reviewNote', String(body.note).trim()); if (body.decision === 'APPROVE') { movement.set('esgTags', JSON.stringify(body.esgTags)); movement.set('publishedAt', now); const leader = new Record(tx.findCollectionByNameOrId('movement_participants')); leader.set('movement', movement.id); leader.set('owner', movement.getString('proposedBy')); leader.set('awardeeId', movement.getString('leaderLegacyId')); leader.set('awardeeName', movement.getString('leaderName')); leader.set('role', 'LEADER'); leader.set('status', 'ACTIVE'); leader.set('joinedAt', now); tx.save(leader); } tx.save(movement); utils.decision(tx, movement, null, e.auth, body.decision, before, after, body.note); result = movement; }); return e.json(200, result);
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/verifier/movement-reports/{id}/start-review', (e) => { const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'VERIFIER'); const report = e.app.findRecordById('movement_reports', e.request.pathValue('id')); if (report.getString('status') !== 'SUBMITTED') throw new BadRequestError('Laporan tidak berada dalam antrean baru.'); const movement = e.app.findRecordById('movements', report.getString('movement')); report.set('status', 'IN_REVIEW'); report.set('reviewer', e.auth.id); report.set('reviewStartedAt', new Date().toISOString()); e.app.save(report); utils.decision(e.app, movement, report, e.auth, 'START_REVIEW', 'SUBMITTED', 'IN_REVIEW', ''); return e.json(200, utils.reportDto(report)); }, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/verifier/movement-reports/{id}/decision', (e) => {
	const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'VERIFIER'); const body = new DynamicModel({ decision: '', note: '' }); e.bindBody(body); if (!['APPROVE','REQUEST_REVISION','REJECT'].includes(body.decision)) throw new BadRequestError('Keputusan tidak dikenal.'); if (body.decision !== 'APPROVE' && String(body.note).trim().length < 5) throw new BadRequestError('Catatan keputusan minimal 5 karakter.'); let result;
	e.app.runInTransaction((tx) => { const report = tx.findRecordById('movement_reports', e.request.pathValue('id')); if (!['SUBMITTED','IN_REVIEW'].includes(report.getString('status'))) throw new BadRequestError('Laporan tidak lagi menunggu keputusan.'); const movement = tx.findRecordById('movements', report.getString('movement')); const before = report.getString('status'); const after = body.decision === 'APPROVE' ? 'APPROVED' : body.decision === 'REJECT' ? 'REJECTED' : 'NEEDS_REVISION'; report.set('status', after); report.set('reviewer', e.auth.id); report.set('reviewNote', String(body.note).trim()); report.set('reviewedAt', new Date().toISOString()); let points = 0; if (body.decision === 'APPROVE' && report.getString('role') === 'LEADER') { try { tx.findFirstRecordByFilter('verified_point_activities', 'movement = {:movement} && user = {:owner} && (actionCode = "LEAD_ACTION" || activityType = "LEAD_ACTION")', { movement: movement.id, owner: report.getString('owner') }); } catch (_) { const actionUtils=require(`${__hooks}/point-action-utils.js`),action=actionUtils.byCode(tx,'LEAD_ACTION',true),ledger = new Record(tx.findCollectionByNameOrId('verified_point_activities')); points = action.getInt('points'); ledger.set('user', report.getString('owner')); ledger.set('source', 'MOVEMENT'); ledger.set('movement', movement.id); ledger.set('movementReport', report.id); ledger.set('awardeeId', report.getString('awardeeId')); actionUtils.attach(ledger,action); ledger.set('points', points); ledger.set('occurredAt', report.getString('activityDate')); ledger.set('awardedAt', new Date().toISOString()); ledger.set('status', 'AWARDED'); tx.save(ledger); try { const awardee = tx.findFirstRecordByData('awardees', 'user', report.getString('owner')); require(`${__hooks}/gamification-utils.js`).ensureProfile(tx, awardee); } catch (_) {} } } report.set('awardedPoints', points); tx.save(report); utils.decision(tx, movement, report, e.auth, body.decision, before, after, body.note); result = report; }); return e.json(200, utils.reportDto(result));
}, $apis.requireAuth('users'));

routerAdd('POST', '/api/pfriends/verifier/movements/{id}/complete', (e) => { const utils = require(`${__hooks}/movement-utils.js`); utils.requireRole(e, 'VERIFIER'); const movement = e.app.findRecordById('movements', e.request.pathValue('id')); if (movement.getString('status') !== 'BERJALAN') throw new BadRequestError('Hanya Gerakan berjalan yang dapat diselesaikan.'); const approved = e.app.findRecordsByFilter('movement_reports', 'movement = {:movement} && status = "APPROVED"', '', 1, 0, { movement: movement.id }); if (!approved.length) throw new BadRequestError('Gerakan membutuhkan minimal satu laporan yang disetujui.'); movement.set('status', 'SELESAI'); e.app.save(movement); utils.decision(e.app, movement, null, e.auth, 'COMPLETE', 'BERJALAN', 'SELESAI', ''); return e.json(200, movement); }, $apis.requireAuth('users'));
