onRecordAfterCreateSuccess((e)=>{try{const awardee=e.app.findFirstRecordByData('awardees','legacyId',e.record.getString('awardeeId'));require(`${__hooks}/gamification-utils.js`).ensureProfile(e.app,awardee);}catch(_){}e.next();},'verified_point_activities');

routerAdd('GET','/api/pfriends/gamification/me',(e)=>{
	if(!e.auth||e.auth.getString('role')!=='AWARDEE')throw new ForbiddenError('Sesi Awardee diperlukan.');
	const utils=require(`${__hooks}/gamification-utils.js`),awardee=e.app.findFirstRecordByData('awardees','user',e.auth.id),result=utils.ensureProfile(e.app,awardee),wallet=require(`${__hooks}/reward-utils.js`).syncWallet(e.app,awardee),badges=e.app.findRecordsByFilter('awardee_badges','awardee = {:awardee} && status = "ACTIVE"','awardedAt',0,0,{awardee:awardee.id}),catalog=e.app.findRecordsByFilter('badges','community = "" || community = {:community}','name',0,0,{community:awardee.getString('community')});
	return e.json(200,{profile:result.profile,wallet:{balance:wallet.getInt('balance'),lifetimeEarned:wallet.getInt('lifetimeEarned'),lifetimeSpent:wallet.getInt('lifetimeSpent')},tiers:utils.tiers(e.app),actions:e.app.findRecordsByFilter('point_actions','status = "ACTIVE"','actionClass,label',0,0).map(require(`${__hooks}/point-action-utils.js`).dto),dailyUsage:utils.dailyUsage(e.app,awardee.getString('legacyId')),ledger:result.entries.slice().reverse(),badges:catalog.map((badge)=>({id:badge.id,code:badge.getString('code'),name:badge.getString('name'),family:badge.getString('family'),rarity:badge.getString('rarity'),criteria:badge.getString('criteria'),icon:badge.getString('icon'),community:badge.getString('community'),unlocked:badges.some((row)=>row.getString('badgeCode')===badge.getString('code'))}))});
},$apis.requireAuth('users'));

routerAdd('GET','/api/pfriends/gamification/leaderboard',(e)=>{
	if(!e.auth)throw new ForbiddenError('Sesi diperlukan.');
	const scope=e.request.url.query().get('scope')||'global',key=e.request.url.query().get('key')||'',period=e.request.url.query().get('period')||'all',limit=Math.min(100,Math.max(1,Number(e.request.url.query().get('limit')||20))),all=require(`${__hooks}/gamification-utils.js`).ensureAll(e.app),month=new Date().toISOString().slice(0,7);let rows=all.map((item)=>{let points=item.profile.getInt('totalPoints');if(period==='month')points=item.entries.filter((entry)=>entry.getString('occurredAt').slice(0,7)===month).reduce((sum,entry)=>sum+entry.getInt('points'),0);return{profile:item.profile,points};}).filter((row)=>row.points>0);
	if(scope==='community')rows=rows.filter((row)=>row.profile.getString('community')===key);if(scope==='chapter')rows=rows.filter((row)=>row.profile.getString('chapterId')===key);rows.sort((a,b)=>b.points-a.points||a.profile.getString('fullName').localeCompare(b.profile.getString('fullName')));
	return e.json(200,{entries:rows.slice(0,limit).map((row,index)=>({rank:index+1,awardeeId:row.profile.getString('awardeeId'),name:row.profile.getBool('anonymousOnLeaderboard')?'Peserta anonim':row.profile.getString('fullName'),community:row.profile.getString('community'),chapterId:row.profile.getString('chapterId'),points:row.points,tier:row.profile.getString('tier'),streakWeeks:row.profile.getInt('currentStreakWeeks')}))});
},$apis.requireAuth('users'));

routerAdd('GET','/api/pfriends/verifier/dashboard',(e)=>{if(!e.auth||e.auth.getString('role')!=='VERIFIER')throw new ForbiddenError('Hanya Verifikator yang dapat membuka dasbor ini.');return e.json(200,require(`${__hooks}/verifier-dashboard-utils.js`).dashboard(e.app,e.auth));},$apis.requireAuth('users'));

routerAdd('POST','/api/pfriends/point-activities/{id}/revoke',(e)=>{if(!e.auth||e.auth.getString('role')!=='ADMIN')throw new ForbiddenError('Hanya Admin yang dapat mencabut poin.');const body=new DynamicModel({reason:''});e.bindBody(body);const reason=String(body.reason||'').trim();if(reason.length<5)throw new BadRequestError('Alasan minimal lima karakter.');const row=e.app.findRecordById('verified_point_activities',e.request.pathValue('id'));if(row.getString('status')!=='AWARDED')throw new BadRequestError('Poin ini sudah dicabut.');row.set('status','REVOKED');row.set('revokedAt',new Date().toISOString());row.set('revokeReason',reason);row.set('revokedBy',e.auth.id);e.app.save(row);const awardee=e.app.findFirstRecordByData('awardees','legacyId',row.getString('awardeeId'));require(`${__hooks}/gamification-utils.js`).ensureProfile(e.app,awardee);return e.json(200,{status:'REVOKED'});},$apis.requireAuth('users'));
