<script>
	import Button from './Button.svelte';
	import Icon from './Icon.svelte';
	import StatusBadge from './StatusBadge.svelte';
	import { ICONS } from '$lib/data/icons.js';
	import { forum } from '$lib/stores/forum.svelte.js';
	let { open=false, initialUserId='', onclose=()=>{} } = $props();
	let query=$state(''), statusFilter=$state(''), selected=$state(null), action=$state('TIMEOUT'), duration=$state('5'), customUntil=$state(''), reason=$state(''), confirmIdentity=$state(''), error=$state(''), success=$state(''), timer, loadedForOpen=false;
	const statusLabel=(item)=>item.accountStatus==='NONAKTIF'?'Akun nonaktif':item.moderation.mode==='BANNED'?'Diban':item.moderation.mode==='TIMEOUT'?'Timeout':'Aktif';
	const dateTime=(value)=>value?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value)):'—';
	async function load(){try{error='';const directUserId=initialUserId&&!selected&&!query.trim()&&!statusFilter?initialUserId:'';await forum.loadModerationUsers(query.trim(),statusFilter,directUserId);if(directUserId){const target=forum.moderationUsers.find(row=>row.id===directUserId);if(target)await choose(target)}}catch(err){error=err instanceof Error?err.message:'Daftar Awardee gagal dimuat.'}}
	$effect(()=>{if(!open){loadedForOpen=false;selected=null;query='';statusFilter='';reason='';confirmIdentity='';success='';error='';return}if(!loadedForOpen){loadedForOpen=true;void load()}});
	$effect(()=>{if(!open)return;query;statusFilter;clearTimeout(timer);timer=setTimeout(load,query?350:0);return()=>clearTimeout(timer)});
	async function choose(item){selected=item;reason='';confirmIdentity='';success='';error='';action=item.moderation.mode==='BANNED'?'UNBAN':item.moderation.mode==='TIMEOUT'?'CLEAR_TIMEOUT':'TIMEOUT';await forum.loadModerationHistory(item.id)}
	function expiresAt(){if(duration==='custom')return customUntil?new Date(customUntil).toISOString():'';return new Date(Date.now()+Number(duration)*60000+5000).toISOString()}
	async function apply(){if(!selected)return;error='';success='';try{const updated=await forum.moderate(selected.id,{action,reason,expiresAt:action==='TIMEOUT'?expiresAt():'',confirmIdentity});selected=updated;success='Tindakan moderasi berhasil disimpan.'}catch(err){error=err instanceof Error?err.message:'Tindakan moderasi gagal disimpan.'}}
</script>

{#if open}
	<div class="fixed inset-0 z-[70] grid place-items-center bg-black/55 p-3" role="presentation">
		<div class="flex max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-card bg-white shadow-2xl" role="dialog" aria-modal="true" aria-label="Panel moderasi Forum">
			<header class="flex items-center justify-between border-b border-ink-100 px-5 py-4"><div><p class="label-micro">Khusus staf</p><h2 class="mt-1 text-xl font-bold text-heading">Moderasi Forum</h2></div><button type="button" class="inline-flex h-10 w-10 items-center justify-center rounded-xl text-ink-600 hover:bg-ink-50" aria-label="Tutup panel moderasi" onclick={onclose}><Icon path={ICONS.x} size={18}/></button></header>
			<div class="grid min-h-0 flex-1 md:grid-cols-[19rem_minmax(0,1fr)]">
				<aside class="min-h-0 border-b border-ink-100 p-4 md:border-r md:border-b-0"><label class="text-xs font-semibold text-ink-700">Cari Awardee<input class="mt-1 w-full rounded-control border border-ink-200 px-3 py-2 text-sm" bind:value={query} placeholder="Nama atau email" /></label><label class="mt-3 block text-xs font-semibold text-ink-700">Status<select class="mt-1 w-full rounded-control border border-ink-200 px-3 py-2 text-sm" bind:value={statusFilter}><option value="">Semua status</option><option value="NONE">Aktif</option><option value="TIMEOUT">Timeout</option><option value="BANNED">Diban</option></select></label>
					<div class="mt-3 max-h-56 space-y-1 overflow-y-auto md:max-h-[55vh]">{#each forum.moderationUsers as item (item.id)}<button type="button" class="block w-full rounded-xl px-3 py-2 text-left {selected?.id===item.id?'bg-brand-50 ring-1 ring-brand-200':'hover:bg-ink-50'}" onclick={()=>choose(item)}><span class="block truncate text-sm font-semibold text-heading">{item.name}</span><span class="block truncate text-xs text-ink-500">{item.email}</span><span class="mt-1 block text-[11px] text-ink-500">{statusLabel(item)}</span></button>{/each}</div>
				</aside>
				<div class="min-h-0 overflow-y-auto p-5">{#if error}<p class="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>{/if}{#if success}<p class="mb-4 rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800" role="status">{success}</p>{/if}
					{#if !selected}<p class="py-12 text-center text-sm text-ink-500">Pilih Awardee untuk melihat status dan tindakan moderasi.</p>{:else}<div class="flex flex-wrap items-center gap-2"><h3 class="mr-auto text-lg font-bold text-heading">{selected.name}</h3><StatusBadge label={statusLabel(selected)} color={selected.moderation.mode==='BANNED'?'red':selected.moderation.mode==='TIMEOUT'?'amber':selected.accountStatus==='NONAKTIF'?'slate':'green'} withDot /></div><p class="mt-1 text-sm text-ink-600">{selected.email} · {selected.community} · {selected.chapterId}</p>{#if selected.moderation.readOnly}<p class="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{selected.moderation.reason}{#if selected.moderation.timeoutUntil}<span class="block text-xs">Berakhir {dateTime(selected.moderation.timeoutUntil)}</span>{/if}</p>{/if}
						<div class="mt-5 border-t border-ink-100 pt-5"><label class="text-sm font-semibold text-ink-700">Tindakan<select class="mt-1 w-full rounded-control border border-ink-200 p-2 font-normal" bind:value={action}><option value="TIMEOUT">Beri timeout</option><option value="CLEAR_TIMEOUT">Cabut timeout</option><option value="BAN">Ban dari Forum</option><option value="UNBAN">Cabut ban dan reset strike</option><option value="DEACTIVATE_ACCOUNT">Nonaktifkan akun PFriends</option></select></label>{#if action==='TIMEOUT'}<label class="mt-3 block text-sm font-semibold text-ink-700">Durasi<select class="mt-1 w-full rounded-control border border-ink-200 p-2 font-normal" bind:value={duration}><option value="5">5 menit</option><option value="30">30 menit</option><option value="360">6 jam</option><option value="1440">24 jam</option><option value="10080">7 hari</option><option value="custom">Waktu khusus</option></select></label>{#if duration==='custom'}<label class="mt-3 block text-sm font-semibold text-ink-700">Berakhir pada<input type="datetime-local" class="mt-1 w-full rounded-control border border-ink-200 p-2 font-normal" bind:value={customUntil}/></label>{/if}{/if}<label class="mt-3 block text-sm font-semibold text-ink-700">Alasan<textarea rows="3" maxlength="2000" class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal" bind:value={reason} placeholder="Minimal 10 karakter"></textarea></label>{#if action==='DEACTIVATE_ACCOUNT'}<div class="mt-3 rounded-xl border border-red-200 bg-red-50 p-3"><p class="text-sm font-semibold text-red-900">Tindakan ini mencabut seluruh sesi dan akses akun.</p><label class="mt-2 block text-xs font-semibold text-red-900">Ketik email untuk konfirmasi<input class="mt-1 w-full rounded-control border border-red-200 bg-white p-2 font-normal" bind:value={confirmIdentity}/></label></div>{/if}<div class="mt-4"><Button disabled={forum.moderating||reason.trim().length<10||(action==='DEACTIVATE_ACCOUNT'&&confirmIdentity.toLowerCase()!==selected.email.toLowerCase())||(action==='TIMEOUT'&&duration==='custom'&&!customUntil)} onclick={apply}>{forum.moderating?'Menyimpan...':'Terapkan tindakan'}</Button></div></div>
						<div class="mt-6 border-t border-ink-100 pt-4"><h4 class="text-sm font-bold text-heading">Riwayat moderasi</h4>{#if forum.moderationHistory.length===0}<p class="mt-2 text-sm text-ink-500">Belum ada tindakan.</p>{:else}<div class="mt-2 space-y-2">{#each forum.moderationHistory as item (item.id)}<div class="rounded-xl bg-ink-50 p-3"><p class="text-xs font-bold text-ink-800">{item.action.replaceAll('_',' ')}</p><p class="mt-1 text-[11px] text-ink-500">{item.actorName} · {dateTime(item.occurredAt)}</p><p class="mt-1 text-sm text-ink-700">{item.reason}</p></div>{/each}</div>{/if}</div>{/if}
				</div>
			</div>
		</div>
	</div>
{/if}
