<script>
	import { onMount } from 'svelte';
	import { deletePointAction, pointActionAudit, savePointAction, staffPointActions } from '$lib/infrastructure/pocketbase/point-actions.js';
	import { toast, ToastType } from '$lib/stores/toast.svelte.js';
	import Button from './Button.svelte'; import Card from './Card.svelte'; import EmptyState from './EmptyState.svelte'; import Modal from './Modal.svelte'; import PointsChip from './PointsChip.svelte'; import StatusBadge from './StatusBadge.svelte';
	const empty=()=>({label:'',description:'',actionClass:'C',pillar:'',points:1,dailyCap:1,status:'ACTIVE'});
	let rows=$state.raw([]), audits=$state.raw([]), loading=$state(true), saving=$state(false), editingId=$state(''), auditTitle=$state(''), form=$state(empty());
	async function load(){loading=true;try{rows=(await staffPointActions()).actions||[]}catch(error){toast.error('Katalog aksi gagal dimuat',error.message)}finally{loading=false}}
	onMount(load); function create(){editingId='NEW';form=empty()} function edit(row){editingId=row.id;form={...empty(),...row}} function close(){if(!saving){editingId='';form=empty()}}
	async function submit(){saving=true;try{await savePointAction($state.snapshot(form),editingId==='NEW'?'':editingId);toast.push({type:ToastType.SUCCESS,title:'Aksi tersimpan'});close();await load()}catch(error){toast.error('Aksi gagal disimpan',error.message)}finally{saving=false}}
	async function remove(row){if(!confirm(`Hapus atau nonaktifkan aksi "${row.label}"?`))return;try{const result=await deletePointAction(row.id);toast.push({type:ToastType.SUCCESS,title:result.archived?'Aksi dinonaktifkan':'Aksi dihapus'});await load()}catch(error){toast.error('Aksi gagal dihapus',error.message)}}
	async function audit(row){auditTitle=row.label;audits=(await pointActionAudit(row.id)).audits||[]}
</script>
<Card class="mb-6" variant="flush" padding="none"><div class="flex flex-wrap items-start justify-between gap-3 p-4"><div><h2 class="text-base font-bold text-heading">Kelola katalog aksi</h2><p class="mt-1 text-sm text-ink-600">Admin dan Verifikator dapat menambah aksi berbukti serta mengatur poin, kuota, dan status.</p></div><Button size="sm" onclick={create}>Tambah aksi</Button></div>
{#if !loading&&rows.length===0}<div class="p-4"><EmptyState title="Katalog aksi kosong" message="Tambahkan aksi pertama untuk Awardee." /></div>{:else}<div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-ink-50"><tr><th class="px-4 py-3">Aksi</th><th class="px-4 py-3">Kelas</th><th class="px-4 py-3">Poin</th><th class="px-4 py-3">Kuota</th><th class="px-4 py-3">Alur</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Kelola</th></tr></thead><tbody>{#each rows as row(row.id)}<tr class="border-t border-ink-100"><td class="px-4 py-3"><p class="font-semibold text-heading">{row.label}</p><p class="text-xs text-ink-500">{row.code} · {row.pillar}</p></td><td class="px-4 py-3">{row.actionClass}</td><td class="px-4 py-3"><PointsChip points={row.points} currency="PK" size="sm" /></td><td class="px-4 py-3">{row.dailyCap}/hari</td><td class="px-4 py-3">{row.workflow==='EVIDENCE'?'Bukti Keaktifan':'Sistem'}</td><td class="px-4 py-3"><StatusBadge label={row.status==='ACTIVE'?'Aktif':'Nonaktif'} color={row.status==='ACTIVE'?'green':'slate'} size="sm" /></td><td class="px-4 py-3"><div class="flex justify-end gap-2"><Button size="sm" variant="ghost" onclick={()=>audit(row)}>Audit</Button><Button size="sm" variant="secondary" onclick={()=>edit(row)}>Ubah</Button><Button size="sm" variant="ghost" onclick={()=>remove(row)}>Hapus</Button></div></td></tr>{/each}</tbody></table></div>{/if}</Card>
<Modal open={editingId!==''} title={editingId==='NEW'?'Tambah aksi berbukti':'Ubah aksi'} size="lg" onclose={close}><div class="grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2 text-sm font-semibold">Nama aksi<input bind:value={form.label} class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal" /></label><label class="sm:col-span-2 text-sm font-semibold">Deskripsi<textarea bind:value={form.description} rows="3" class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal"></textarea></label><label class="text-sm font-semibold">Kelas<select bind:value={form.actionClass} class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal">{#if form.isCore}<option value="A">A</option>{/if}<option value="B">B</option><option value="C">C</option><option value="D">D</option></select></label><label class="text-sm font-semibold">Pilar<input bind:value={form.pillar} class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal" /></label><label class="text-sm font-semibold">Poin<input type="number" min="1" max="999" bind:value={form.points} class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal" /></label><label class="text-sm font-semibold">Kuota per hari<input type="number" min="1" max="100" bind:value={form.dailyCap} class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal" /></label><label class="text-sm font-semibold">Status<select bind:value={form.status} class="mt-1 w-full rounded-control border border-ink-200 p-3 font-normal"><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option></select></label>{#if editingId!=='NEW'}<p class="self-end text-xs text-ink-500">Kode dan alur aksi dikunci agar riwayat tetap konsisten.</p>{/if}</div>{#snippet footer()}<Button variant="ghost" onclick={close}>Batal</Button><Button loading={saving} disabled={form.label.trim().length<3||form.description.trim().length<10||form.pillar.trim().length<3} onclick={submit}>Simpan aksi</Button>{/snippet}</Modal>
<Modal open={auditTitle!==''} title={`Riwayat perubahan · ${auditTitle}`} onclose={()=>{auditTitle='';audits=[]}}>{#if audits.length===0}<EmptyState title="Belum ada perubahan" message="Riwayat perubahan aksi akan tampil di sini." />{:else}<div class="grid gap-3">{#each audits as item}<div class="rounded-xl border border-ink-100 p-3"><div class="flex justify-between gap-3"><strong>{item.operation}</strong><span class="text-xs text-ink-500">{new Date(item.occurredAt).toLocaleString('id-ID')}</span></div><p class="mt-1 text-sm text-ink-600">{item.actorName} · {item.actorRole}</p></div>{/each}</div>{/if}</Modal>
